/**
 *
 *  Class Filter.java
 *
 *  Generated by KMFStudio at 22 July 2003 18:50:16
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.yatl.syntax.transformations;

import java.util.List;

import uk.ac.kent.cs.yatl.YatlElement;

public interface Filter
extends
    YatlElement
{

	/** Get the 'pathName' from 'Filter' */
	public List getPathName();
	/** Set the 'pathName' from 'Filter' */
	public void setPathName(List pathName);

	/** Get the 'expression' from 'Filter' */
	public Object getExpression();
	/** Set the 'expression' from 'Filter' */
	public void setExpression(Object expression);

	/** Get the 'rule' from 'Filter' */
	public Rule getRule();
	/** Set the 'rule' from 'Filter' */
	public void setRule(Rule rule);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
