/**
 *
 *  Class NamedElement.java
 *
 *  Generated by KMFStudio at 22 July 2003 18:50:16
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.yatl.syntax.transformations;

import uk.ac.kent.cs.yatl.YatlElement;

public interface NamedElement
extends
    YatlElement
{

	/** Get the 'name' from 'NamedElement' */
	public String getName();
	/** Set the 'name' from 'NamedElement' */
	public void setName(String name);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
