/**
 *
 *  Class Unit.java
 *
 *  Generated by KMFStudio at 22 July 2003 18:50:16
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.yatl.syntax.transformations;

import java.util.List;

import uk.ac.kent.cs.yatl.YatlElement;

public interface Unit
extends
    YatlElement
{

	/** Get the 'startPathName' from 'Unit' */
	public List getStartPathName();
	/** Set the 'startPathName' from 'Unit' */
	public void setStartPathName(List startPathName);

	/** Get the 'imports' from 'Unit' */
	public List getImports();
	/** Set the 'imports' from 'Unit' */
	public void setImports(List imports);

	/** Get the 'startRule' from 'Unit' */
	public Rule getStartRule();
	/** Set the 'startRule' from 'Unit' */
	public void setStartRule(Rule startRule);

	/** Get the 'namespaces' from 'Unit' */
	public List getNamespaces();
	/** Set the 'namespaces' from 'Unit' */
	public void setNamespaces(List namespaces);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
