/**
 *
 *  Class SdViewVisitor.java
 *
 *  Generated by KMFStudio at 18 February 2004 20:38:46
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.repository;

import sd.*;

public interface SdViewVisitor
  extends SdVisitor
{
}
