/**
 *
 *  Class wsStartup.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:41
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.startup;

public class WsStartup$Class
	implements WsStartup
{
	//--- The repository ---
	protected ws.repository.WsRepository rep;
	public ws.repository.WsRepository getRepository() {
		return rep;
	}
	public void setRepository(ws.repository.WsRepository rep) {
		this.rep = rep;
	}

	//--- Replace the default lifecycle handlers ---
	protected void replaceDefaultLifecycles() {
	}

	//--- Initialise population ---
	protected void initialisePopulation() {
	}

	//--- Start the 'ws' browser ---
	protected void startBrowser() {
		new ws.repository.WsBrowser$Class("C:/D/Work/Java Projects/YATL4KMF/src/test/scripts/WS.xmi");
		ws.repository.WsBrowser$Class browser = new ws.repository.WsBrowser$Class("C:/D/Work/Java Projects/YATL4KMF/src/test/scripts/WS.xmi");
		browser.setRep(rep);
		browser.show();
	}

	//--- run ---
	public void run(ws.repository.WsRepository rep) {
		setRepository(rep);
		replaceDefaultLifecycles();
		initialisePopulation();
		startBrowser();
	}

	//--- Main ---
	public static void main(String args[]) {
		(new WsStartup$Class()).run(new ws.repository.WsRepository$Class());
	}
}
