/**
 *
 *  Class OrderedSetTypeASFactory.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:44
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.types;

public interface OrderedSetTypeASFactory
extends
    ocl.syntax.SyntaxFactory
{
	/** Default builder */
	public Object build();
}
