/**
 *
 *  Class TupleTypeAS$Factory.java
 *
 *  Generated by KMFStudio at 25 November 2003 13:00:53
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.types;

public interface TupleTypeAS$Factory
extends
    ocl.syntax.SyntaxFactory
{
	/** Default builder */
	public Object build();
}
