/**
 *
 *  Class CollectionRangeAS.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:43
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public interface CollectionRangeAS
extends
    ocl.syntax.SyntaxElement,
    CollectionLiteralPartAS
{

	/** Get the 'first' from 'CollectionRangeAS' */
	public OclExpressionAS getFirst();
	/** Set the 'first' from 'CollectionRangeAS' */
	public void setFirst(OclExpressionAS first);

	/** Get the 'last' from 'CollectionRangeAS' */
	public OclExpressionAS getLast();
	/** Set the 'last' from 'CollectionRangeAS' */
	public void setLast(OclExpressionAS last);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
