/**
 *
 *  Class CollectionKindAS$Factory.java
 *
 *  Generated by KMFStudio at 25 November 2003 13:00:52
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public interface CollectionKindAS$Factory
extends
    ocl.syntax.SyntaxFactory
{
	/** Default builder */
	public Object build();
}
