/**
 *
 *  Class CollectionRangeAS$Factory$Class.java
 *
 *  Generated by KMFStudio at 25 November 2003 13:00:52
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public class CollectionRangeAS$Factory$Class
	extends ocl.syntax.SyntaxFactory$Class
	implements CollectionRangeAS$Factory
{
	/** Default factory constructor */
	public CollectionRangeAS$Factory$Class() {
	}
	public CollectionRangeAS$Factory$Class(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		CollectionRangeAS obj = new CollectionRangeAS$Class();
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.expressions.CollectionRangeAS", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "CollectionRangeAS_Factory";
	}

	/** Accept 'ocl.syntax.ast.expressions.CollectionRangeAS$Visitor' */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
