/**
 *
 *  Class CollectionKindAS$Class.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:43
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public class CollectionKindAS$Class
implements
    CollectionKindAS,
    ocl.syntax.SyntaxVisitable
{
	/** The 'SET' enumerator */
	public static final CollectionKindAS SET = new CollectionKindAS$Class();
	/** The 'BAG' enumerator */
	public static final CollectionKindAS BAG = new CollectionKindAS$Class();
	/** The 'SEQUENCE' enumerator */
	public static final CollectionKindAS SEQUENCE = new CollectionKindAS$Class();
	/** The 'COLLECTION' enumerator */
	public static final CollectionKindAS COLLECTION = new CollectionKindAS$Class();
	/** The 'ORDERED_SET' enumerator */
	public static final CollectionKindAS ORDERED_SET = new CollectionKindAS$Class();

	/** Default constructors */
	public CollectionKindAS$Class() {
	}

	/** The id */
	protected String id;
	/** Get the id */
	public String getId() {
		return id;
	}
	/** Set the id */
	public void setId(String id) {
		this.id = "1";
	}

	/** Overrride toString */
	public String toString() {
		String res = "CollectionKindAS";
		if (this == SET) res += "::SET";
		if (this == BAG) res += "::BAG";
		if (this == SEQUENCE) res += "::SEQUENCE";
		if (this == COLLECTION) res += "::COLLECTION";
		if (this == ORDERED_SET) res += "::ORDERED_SET";
		return res;
	}
	/** Clone the object */
	public Object clone() {
		CollectionKindAS$Class obj = new CollectionKindAS$Class();
		return obj;
	}
	/** Delete the object */
	public void delete() {
	}

	/** Accept the visitor */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object obj) {
		return v.visit(this, obj);
	}
}
