/**
 *
 *  Class CollectionItemAS$Class.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:43
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public class CollectionItemAS$Class
implements
	CollectionItemAS,
    ocl.syntax.SyntaxVisitable
{
	/** Default constructor */
	public CollectionItemAS$Class() {
		//--- Set property 'collectionLiteralExpAS' from 'CollectionLiteralPartAS' ---
		this.collectionLiteralExpAS = null;
		//--- Set property 'item' from 'CollectionItemAS' ---
		this.item = null;
	}


	/** Property 'collectionLiteralExpAS' from 'CollectionLiteralPartAS' */
	protected CollectionLiteralExpAS collectionLiteralExpAS;
	/** Get property 'collectionLiteralExpAS' from 'CollectionLiteralPartAS' */
	public CollectionLiteralExpAS getCollectionLiteralExpAS() {
		return collectionLiteralExpAS;
	}
	/** Set property 'collectionLiteralExpAS' from 'CollectionLiteralPartAS' */
	public void setCollectionLiteralExpAS(CollectionLiteralExpAS collectionLiteralExpAS) { 
		this.collectionLiteralExpAS = collectionLiteralExpAS;
	}

	/** Property 'item' from 'CollectionItemAS' */
	protected OclExpressionAS item;
	/** Get property 'item' from 'CollectionItemAS' */
	public OclExpressionAS getItem() {
		return item;
	}
	/** Set property 'item' from 'CollectionItemAS' */
	public void setItem(OclExpressionAS item) { 
		this.item = item;
	}

	/** The id */
	protected String id;
	/** Get the id */
	public String getId() {
		return id;
	}
	/** Set the id */
	public void setId(String id) {
		this.id = id;
	}

	/** Override toString */
	public String toString() {
		String strId = "syntax.ast.expressions.CollectionItemAS";
		String name = null;
		try {
			java.lang.Class cls = this.getClass();
			java.lang.reflect.Method method = cls.getMethod("getName", new java.lang.Class[] {});
			name = (String) method.invoke(this, new Object[] {});
			if (name != null && name.length()==0) name = null;
		} catch (Exception e) {
		}
		if (name == null)
			return strId+" 'id-"+getId()+"'";
		else
			return strId+" '"+name+"-"+getId()+"'";
	}

	/** Delete the object */
	public void delete() {
		if (collectionLiteralExpAS != null)
			this.collectionLiteralExpAS.getCollectionParts().remove(this);
		if (item != null)
			this.item.setCollectionItemAS(null);
	}

	/** Clone the object */
	public Object clone() {
		CollectionItemAS$Class obj = new CollectionItemAS$Class();
		obj.collectionLiteralExpAS = collectionLiteralExpAS==null ? null : this.collectionLiteralExpAS;
		obj.item = item==null ? null : this.item;
		return obj;
	}

	/** Accept 'ocl.syntax.ast.expressions.CollectionItemASVisitor' */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
