/**
 *
 *  Class EnumLiteralExpASFactory$Class.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:44
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public class EnumLiteralExpASFactory$Class
	extends ocl.syntax.SyntaxFactory$Class
	implements EnumLiteralExpASFactory
{
	/** Default factory constructor */
	public EnumLiteralExpASFactory$Class() {
	}
	public EnumLiteralExpASFactory$Class(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		EnumLiteralExpAS obj = new EnumLiteralExpAS$Class();
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.expressions.EnumLiteralExpAS", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(Boolean isMarkedPre, java.util.List pathName) {
		EnumLiteralExpAS obj = new EnumLiteralExpAS$Class(isMarkedPre, pathName);
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.expressions.EnumLiteralExpAS", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "EnumLiteralExpASFactory";
	}

	/** Accept 'ocl.syntax.ast.expressions.EnumLiteralExpASVisitor' */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
