/**
 *
 *  Class IfExpAS.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:44
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public interface IfExpAS
extends
    ocl.syntax.SyntaxElement,
    OclExpressionAS
{

	/** Get the 'thenExpression' from 'IfExpAS' */
	public OclExpressionAS getThenExpression();
	/** Set the 'thenExpression' from 'IfExpAS' */
	public void setThenExpression(OclExpressionAS thenExpression);

	/** Get the 'elseExpression' from 'IfExpAS' */
	public OclExpressionAS getElseExpression();
	/** Set the 'elseExpression' from 'IfExpAS' */
	public void setElseExpression(OclExpressionAS elseExpression);

	/** Get the 'condition' from 'IfExpAS' */
	public OclExpressionAS getCondition();
	/** Set the 'condition' from 'IfExpAS' */
	public void setCondition(OclExpressionAS condition);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
