/**
 *
 *  Class OclMessageKindASFactory$Class.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:44
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public class OclMessageKindASFactory$Class
	extends ocl.syntax.SyntaxFactory$Class
	implements OclMessageKindASFactory
{
	/** Default factory constructor */
	public OclMessageKindASFactory$Class() {
	}
	public OclMessageKindASFactory$Class(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		OclMessageKindAS obj = new OclMessageKindAS$Class();
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.expressions.OclMessageKindAS", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "OclMessageKindASFactory";
	}

	/** Accept 'ocl.syntax.ast.expressions.OclMessageKindASVisitor' */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
