/**
 *
 *  Class OclMessageExpAS$Factory$Class.java
 *
 *  Generated by KMFStudio at 25 November 2003 13:00:52
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public class OclMessageExpAS$Factory$Class
	extends ocl.syntax.SyntaxFactory$Class
	implements OclMessageExpAS$Factory
{
	/** Default factory constructor */
	public OclMessageExpAS$Factory$Class() {
	}
	public OclMessageExpAS$Factory$Class(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		OclMessageExpAS obj = new OclMessageExpAS$Class();
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.expressions.OclMessageExpAS", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(Boolean isMarkedPre, String name, ocl.syntax.ast.expressions.OclMessageKindAS kind) {
		OclMessageExpAS obj = new OclMessageExpAS$Class(isMarkedPre, name, kind);
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.expressions.OclMessageExpAS", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "OclMessageExpAS_Factory";
	}

	/** Accept 'ocl.syntax.ast.expressions.OclMessageExpAS$Visitor' */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
