/**
 *
 *  Class RealLiteralExpASFactory$Class.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:43
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public class RealLiteralExpASFactory$Class
	extends ocl.syntax.SyntaxFactory$Class
	implements RealLiteralExpASFactory
{
	/** Default factory constructor */
	public RealLiteralExpASFactory$Class() {
	}
	public RealLiteralExpASFactory$Class(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		RealLiteralExpAS obj = new RealLiteralExpAS$Class();
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.expressions.RealLiteralExpAS", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(Boolean isMarkedPre, Double value) {
		RealLiteralExpAS obj = new RealLiteralExpAS$Class(isMarkedPre, value);
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.expressions.RealLiteralExpAS", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "RealLiteralExpASFactory";
	}

	/** Accept 'ocl.syntax.ast.expressions.RealLiteralExpASVisitor' */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
