/**
 *
 *  Class SelectionExpAS.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:44
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public interface SelectionExpAS
extends
    ocl.syntax.SyntaxElement,
    OclExpressionAS
{

	/** Get the 'name' from 'SelectionExpAS' */
	public String getName();
	/** Set the 'name' from 'SelectionExpAS' */
	public void setName(String name);

	/** Get the 'source' from 'SelectionExpAS' */
	public OclExpressionAS getSource();
	/** Set the 'source' from 'SelectionExpAS' */
	public void setSource(OclExpressionAS source);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
