/**
 *
 *  Class StringLiteralExpAS$Factory$Class.java
 *
 *  Generated by KMFStudio at 25 November 2003 13:00:52
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.expressions;

public class StringLiteralExpAS$Factory$Class
	extends ocl.syntax.SyntaxFactory$Class
	implements StringLiteralExpAS$Factory
{
	/** Default factory constructor */
	public StringLiteralExpAS$Factory$Class() {
	}
	public StringLiteralExpAS$Factory$Class(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		StringLiteralExpAS obj = new StringLiteralExpAS$Class();
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.expressions.StringLiteralExpAS", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(Boolean isMarkedPre, String value) {
		StringLiteralExpAS obj = new StringLiteralExpAS$Class(isMarkedPre, value);
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.expressions.StringLiteralExpAS", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "StringLiteralExpAS_Factory";
	}

	/** Accept 'ocl.syntax.ast.expressions.StringLiteralExpAS$Visitor' */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
