/**
 *
 *  Class AbstractTransition.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.CCA;

public interface AbstractTransition
extends
    edoc.EdocElement
{

	/** Get the 'owner' from 'AbstractTransition' */
	public Choreography getOwner();
	/** Set the 'owner' from 'AbstractTransition' */
	public void setOwner(Choreography owner);

	/** Get the 'target' from 'AbstractTransition' */
	public Node getTarget();
	/** Set the 'target' from 'AbstractTransition' */
	public void setTarget(Node target);

	/** Get the 'source' from 'AbstractTransition' */
	public Node getSource();
	/** Set the 'source' from 'AbstractTransition' */
	public void setSource(Node source);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
