/**
 *
 *  Class FlowFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.CCA;

public class FlowFactory$Class
	extends edoc.EdocFactory$Class
	implements FlowFactory
{
	/** Default factory constructor */
	public FlowFactory$Class() {
	}
	public FlowFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Flow obj = new Flow$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.Flow", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "FlowFactory";
	}

	/** Accept 'edoc.ECA.CCA.FlowVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
