/**
 *
 *  Class InterfaceFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.CCA;

public class InterfaceFactory$Class
	extends edoc.EdocFactory$Class
	implements InterfaceFactory
{
	/** Default factory constructor */
	public InterfaceFactory$Class() {
	}
	public InterfaceFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Interface obj = new Interface$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.Interface", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		Interface obj = new Interface$Class(name);
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.Interface", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "InterfaceFactory";
	}

	/** Accept 'edoc.ECA.CCA.InterfaceVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
