/**
 *
 *  Class PortOwner.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.CCA;

public interface PortOwner
extends
    edoc.EdocElement
{

	/** Get the 'name' from 'PortOwner' */
	public String getName();
	/** Set the 'name' from 'PortOwner' */
	public void setName(String name);

	/** Get the 'ports' from 'PortOwner' */
	public java.util.Set getPorts();
	/** Set the 'ports' from 'PortOwner' */
	public void setPorts(java.util.Set ports);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
