/**
 *
 *  Class Port.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.CCA;

public interface Port
extends
    edoc.EdocElement
{

	/** Get the 'name' from 'Port' */
	public String getName();
	/** Set the 'name' from 'Port' */
	public void setName(String name);

	/** Get the 'isSynchronous' from 'Port' */
	public Boolean getIsSynchronous();
	/** Set the 'isSynchronous' from 'Port' */
	public void setIsSynchronous(Boolean isSynchronous);

	/** Get the 'isTransactional' from 'Port' */
	public Boolean getIsTransactional();
	/** Set the 'isTransactional' from 'Port' */
	public void setIsTransactional(Boolean isTransactional);

	/** Get the 'direction' from 'Port' */
	public DirectionType getDirection();
	/** Set the 'direction' from 'Port' */
	public void setDirection(DirectionType direction);

	/** Get the 'postCondition' from 'Port' */
	public Status getPostCondition();
	/** Set the 'postCondition' from 'Port' */
	public void setPostCondition(Status postCondition);

	/** Get the 'representedBy' from 'Port' */
	public java.util.Set getRepresentedBy();
	/** Set the 'representedBy' from 'Port' */
	public void setRepresentedBy(java.util.Set representedBy);

	/** Get the 'owner' from 'Port' */
	public PortOwner getOwner();
	/** Set the 'owner' from 'Port' */
	public void setOwner(PortOwner owner);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
