/**
 *
 *  Class ProcessComponentFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.CCA;

public class ProcessComponentFactory$Class
	extends edoc.EdocFactory$Class
	implements ProcessComponentFactory
{
	/** Default factory constructor */
	public ProcessComponentFactory$Class() {
	}
	public ProcessComponentFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		ProcessComponent obj = new ProcessComponent$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.ProcessComponent", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name, edoc.ECA.CCA.GranularityKind granularity, Boolean isPersistent, String primitiveKind, String primitiveSpec) {
		ProcessComponent obj = new ProcessComponent$Class(name, granularity, isPersistent, primitiveKind, primitiveSpec);
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.ProcessComponent", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ProcessComponentFactory";
	}

	/** Accept 'edoc.ECA.CCA.ProcessComponentVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
