/**
 *
 *  Class ProtocolFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.CCA;

public class ProtocolFactory$Class
	extends edoc.EdocFactory$Class
	implements ProtocolFactory
{
	/** Default factory constructor */
	public ProtocolFactory$Class() {
	}
	public ProtocolFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Protocol obj = new Protocol$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.Protocol", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		Protocol obj = new Protocol$Class(name);
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.Protocol", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ProtocolFactory";
	}

	/** Accept 'edoc.ECA.CCA.ProtocolVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
