/**
 *
 *  Class PseudoStateFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.CCA;

public class PseudoStateFactory$Class
	extends edoc.EdocFactory$Class
	implements PseudoStateFactory
{
	/** Default factory constructor */
	public PseudoStateFactory$Class() {
	}
	public PseudoStateFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		PseudoState obj = new PseudoState$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.PseudoState", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name, edoc.ECA.CCA.PseudoStateKind kind) {
		PseudoState obj = new PseudoState$Class(name, kind);
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.PseudoState", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "PseudoStateFactory";
	}

	/** Accept 'edoc.ECA.CCA.PseudoStateVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
