/**
 *
 *  Class TransitionFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.CCA;

public class TransitionFactory$Class
	extends edoc.EdocFactory$Class
	implements TransitionFactory
{
	/** Default factory constructor */
	public TransitionFactory$Class() {
	}
	public TransitionFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Transition obj = new Transition$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.Transition", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(edoc.ECA.CCA.Status precondition) {
		Transition obj = new Transition$Class(precondition);
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.CCA.Transition", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "TransitionFactory";
	}

	/** Accept 'edoc.ECA.CCA.TransitionVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
