/**
 *
 *  Class WsFactoryAdapter$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:41
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.repository;

import uk.ac.kent.cs.kmf.xmi.*;
import uk.ac.kent.cs.kmf.util.*;

public class WsFactoryAdapter$Class
	extends AdapterFactory
	implements IAdapterFactory
{
	/** The repository */
	ws.repository.WsRepository rep;
	/** The log */
	ILog log;

	/** AdapterFactory constructor */
	public WsFactoryAdapter$Class(ws.repository.WsRepository rep, ILog log) {
		this.rep = rep;
		this.log = log;
	}

	/** Create a ReaderAdapter */
	public ReaderAdapter createReaderAdapter() {
		return new WsReaderAdapter$Class(rep, log);
	}

	/** Create a WriterAdapter */
	public WriterAdapter createWriterAdapter() {
		return new WriterAdapter();
	}
}
