/**
 *
 *  Class WsJTreeVisitor.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.repository;

import ws.*;

public interface WsJTreeVisitor
	extends WsVisitor
{
}
