/**
 *
 *  Class DataProbeFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.EntityPkg;

public class DataProbeFactory$Class
	extends edoc.EdocFactory$Class
	implements DataProbeFactory
{
	/** Default factory constructor */
	public DataProbeFactory$Class() {
	}
	public DataProbeFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		DataProbe obj = new DataProbe$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.EntityPkg.DataProbe", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name, Boolean isSynchronous, Boolean isTransactional, edoc.ECA.CCA.DirectionType direction, edoc.ECA.CCA.Status postCondition, Boolean extentProbe) {
		DataProbe obj = new DataProbe$Class(name, isSynchronous, isTransactional, direction, postCondition, extentProbe);
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.EntityPkg.DataProbe", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "DataProbeFactory";
	}

	/** Accept 'edoc.ECA.EntityPkg.DataProbeVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
