/**
 *
 *  Class Key.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.EntityPkg;

public interface Key
extends
    edoc.EdocElement,
    edoc.ECA.DocumentModel.CompositeData,
    edoc.ECA.DocumentModel.DataElement,
    edoc.ECA.ModelManagement.PackageContent
{

	/** Get the 'primaryKey' from 'Key' */
	public Boolean getPrimaryKey();
	/** Set the 'primaryKey' from 'Key' */
	public void setPrimaryKey(Boolean primaryKey);

	/** Get the 'keyElements' from 'Key' */
	public java.util.Set getKeyElements();
	/** Set the 'keyElements' from 'Key' */
	public void setKeyElements(java.util.Set keyElements);

	/** Get the 'owner' from 'Key' */
	public EntityData getOwner();
	/** Set the 'owner' from 'Key' */
	public void setOwner(EntityData owner);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
