/**
 *
 *  Class SyntaxVisitable.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax;

public interface SyntaxVisitable
{
	/** Accept the visitor */
	public Object accept(SyntaxVisitor v, Object obj);
}
