/**
 *
 *  Class SyntaxFactory$Class.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax;

public class SyntaxFactory$Class
	implements SyntaxFactory
{
	/** Default constructor */
	public SyntaxFactory$Class() {
	}
	/** Specialized constructor */
	public SyntaxFactory$Class(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}
	/** Build object */
	public Object build() {
		return null;
	}

	/** The id */
	private static int objId = 0;
	/** Reset the id */
	public static void resetId() {
		objId = 0;
	}
	/** Get a new id */
	public static String newId() {
		return ""+ ++objId;
	}

	/** The repository */
	protected ocl.syntax.repository.SyntaxRepository repository;
	/** Get the repository */
	public ocl.syntax.repository.SyntaxRepository getRepository() {
		return repository;
	}
	/** Set the repository */
	public void setRepository(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}

	/** Override toString */
	public String toString() {
		return "SyntaxFactory";
	}

	/** Accept 'SyntaxVisitor' */
	public Object accept(SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
