/**
 *
 *  Class SyntaxRepository.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:44
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.repository;

import javax.swing.tree.*;

import uk.ac.kent.cs.kmf.util.*;

import ocl.syntax.*;

public interface SyntaxRepository
	extends uk.ac.kent.cs.kmf.common.Repository
{
	///--- FACTORIES ---
	/** Get a specific factory */
	public SyntaxFactory getFactory(String fullClassName);
	/** Register a factory */
	public void registerFactory(String fullClassName, SyntaxFactory factory);

	//--- BROWSER ---
	/** Get the content of the repository */
	public DefaultMutableTreeNode toJTree();
	/** Save the repository into an XMI file */
	public void saveXMI(String fileName);
	/** Create a new repository from an XMI file */
	public uk.ac.kent.cs.kmf.common.Repository loadXMI(String fileName);
	/** Get the content of the repository */
	public String toHUTN();
	/** Save the repository into an HUTN file */
	public void saveHUTN(String fileName);
	/** Create a new repository from an HUTN file */
	public SyntaxRepository loadHUTN(String fileName);

	/** Get the log file */
	public ILog getLog();
	/** Set the log file */
	public void setLog(ILog log);
}
