/**
 *
 *  Class ActivityFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:37
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.BusinessProcessPkg;

public class ActivityFactory$Class
	extends edoc.EdocFactory$Class
	implements ActivityFactory
{
	/** Default factory constructor */
	public ActivityFactory$Class() {
	}
	public ActivityFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Activity obj = new Activity$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.BusinessProcessPkg.Activity", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		Activity obj = new Activity$Class(name);
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.BusinessProcessPkg.Activity", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ActivityFactory";
	}

	/** Accept 'edoc.ECA.BusinessProcessPkg.ActivityVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
