/**
 *
 *  Class BusinessProcessEntityFactory.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:37
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.BusinessProcessPkg;

public interface BusinessProcessEntityFactory
extends
    edoc.EdocFactory
{
	/** Default builder */
	public Object build();
	/** Specialized builder */
	public Object build(String name, edoc.ECA.CCA.GranularityKind granularity, Boolean isPersistent, String primitiveKind, String primitiveSpec, Boolean networkAccess, Boolean shareable, Boolean managed);
}
