/**
 *
 *  Class InputGroup.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:37
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.BusinessProcessPkg;

public interface InputGroup
extends
    edoc.EdocElement,
    ProcessMultiPort,
    edoc.ECA.CCA.MultiPort,
    edoc.ECA.CCA.PortOwner,
    edoc.ECA.CCA.Port
{

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
