/**
 *
 *  Class ProcessRole.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:37
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.BusinessProcessPkg;

public interface ProcessRole
extends
    edoc.EdocElement,
    edoc.ECA.CCA.ComponentUsage,
    edoc.ECA.CCA.UsageContext
{

	/** Get the 'selectionRule' from 'ProcessRole' */
	public String getSelectionRule();
	/** Set the 'selectionRule' from 'ProcessRole' */
	public void setSelectionRule(String selectionRule);

	/** Get the 'creationRule' from 'ProcessRole' */
	public String getCreationRule();
	/** Set the 'creationRule' from 'ProcessRole' */
	public void setCreationRule(String creationRule);

	/** Get the 'artifactFor' from 'ProcessRole' */
	public java.util.Set getArtifactFor();
	/** Set the 'artifactFor' from 'ProcessRole' */
	public void setArtifactFor(java.util.Set artifactFor);

	/** Get the 'performs' from 'ProcessRole' */
	public java.util.Set getPerforms();
	/** Set the 'performs' from 'ProcessRole' */
	public void setPerforms(java.util.Set performs);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
