/**
 *
 *  Class JavaModelRepository$Class.java
 *
 *  Generated by KMFStudio at 22 February 2004 15:13:03
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package javaModel.repository;

import java.io.*;
import java.util.*;
import javax.swing.tree.*;
import uk.ac.kent.cs.kmf.xmi.*;

import javaModel.*;

public class JavaModelRepository$Class
	extends uk.ac.kent.cs.kmf.common.RepositoryImpl
	implements JavaModelRepository
{
	/** Default repository constructor */
	public JavaModelRepository$Class() {
		setLog(new uk.ac.kent.cs.kmf.util.FileLog("Repository.log"));
		init();
	}
	/** Repository constructor */
	public JavaModelRepository$Class(uk.ac.kent.cs.kmf.util.ILog log) {
		setLog(log);
		init();
	}
	/** Init the attributes */
	protected void init() {
		log.reportMessage("Init javaModel repository");
		// Add factories
		log.reportMessage("Adding factory and initializing population for 'javaModel.JavaClass'");
		factories.put("javaModel.JavaClass", new javaModel.JavaClassFactory$Class(this));
		population.put("javaModel.JavaClass", new Vector());
		log.reportMessage("Adding factory and initializing population for 'javaModel.JavaField'");
		factories.put("javaModel.JavaField", new javaModel.JavaFieldFactory$Class(this));
		population.put("javaModel.JavaField", new Vector());
		log.reportMessage("Adding factory and initializing population for 'javaModel.JavaMethod'");
		factories.put("javaModel.JavaMethod", new javaModel.JavaMethodFactory$Class(this));
		population.put("javaModel.JavaMethod", new Vector());
		log.reportMessage("Adding factory and initializing population for 'javaModel.JavaElement'");
		population.put("javaModel.JavaElement", new Vector());
		log.reportMessage("Adding factory and initializing population for 'javaModel.JavaPackage'");
		factories.put("javaModel.JavaPackage", new javaModel.JavaPackageFactory$Class(this));
		population.put("javaModel.JavaPackage", new Vector());
		log.reportMessage("Adding factory and initializing population for 'javaModel.JavaParameter'");
		factories.put("javaModel.JavaParameter", new javaModel.JavaParameterFactory$Class(this));
		population.put("javaModel.JavaParameter", new Vector());
		log.reportMessage("Adding factory and initializing population for 'javaModel.JavaPackageElement'");
		factories.put("javaModel.JavaPackageElement", new javaModel.JavaPackageElementFactory$Class(this));
		population.put("javaModel.JavaPackageElement", new Vector());
		log.reportMessage("Adding factory and initializing population for 'javaModel.JavaInterface'");
		factories.put("javaModel.JavaInterface", new javaModel.JavaInterfaceFactory$Class(this));
		population.put("javaModel.JavaInterface", new Vector());
		log.reportMessage("Adding factory and initializing population for 'javaModel.JavaClassifier'");
		factories.put("javaModel.JavaClassifier", new javaModel.JavaClassifierFactory$Class(this));
		population.put("javaModel.JavaClassifier", new Vector());
		log.reportMessage("Adding factory and initializing population for 'javaModel.DataType'");
		factories.put("javaModel.DataType", new javaModel.DataTypeFactory$Class(this));
		population.put("javaModel.DataType", new Vector());
		log.reportMessage("Adding factory and initializing population for 'javaModel.DataKind'");
		factories.put("javaModel.DataKind", new javaModel.DataKindFactory$Class(this));
		population.put("javaModel.DataKind", new Vector());
	}

	//--- MODEL NAME ---
	protected String modelName = "javaModel";
	public String getModelName() {
		return modelName;
	}

	//--- POPULATION ---
	/** Build an element */
	public Object buildElement(String fullClassName) {
		Object elem = null;
		try {
			JavaModelFactory factory = (JavaModelFactory)factories.get(fullClassName);
			elem = factory.build();
		} catch (Exception e) {
			log.reportMessage("Error: Missing factory for '"+fullClassName+"' class ");
		}
		return elem;
	}
	/** Add an element */
	public void addElement(String fullClassName, Object elem) {
		try {
			((List)population.get(fullClassName)).add(elem);
		} catch (Exception e) {;
			log.reportMessage("Error: Missing population for '"+fullClassName+"' class");
		}
	}
	/** Remove an element */
	public void removeElement(String fullClassName, Object elem) {
		try {
			((List)population.get(fullClassName)).remove(elem);
		} catch (Exception e) {;
			log.reportMessage("Error: Missing population for '"+fullClassName+"' class");
		}
	}
	/** Get all elements of a type */
	public List getElements(String fullClassName) {
		List objs = null;
		try {
			objs = (List)population.get(fullClassName);
		} catch (Exception e) {;
			log.reportMessage("Error: Missing population for '"+fullClassName+"' class");
		}
		return objs;
	}
	/** Check if the first class name is an instance of the second class name */
	protected boolean isInstanceOf(String elemName, String fullClassName) {
		//--- Check if fullClassName is a superinterface of elemName ---
		boolean res = false;
		try {
			res = Class.forName(fullClassName).isAssignableFrom(Class.forName(elemName));
		} catch (Exception e) {
		}
		return res;
	}
	/** Get all instances of a type */
	public List getInstances(String fullClassName) {
		List objs = new Vector();
		Set elemNames = population.keySet();
		Iterator nameIt = elemNames.iterator();
		while (nameIt.hasNext()) {
			String elemName = (String)nameIt.next();
			if (isInstanceOf(elemName, fullClassName)) {
				List elements = (List)population.get(elemName);
				Iterator elemIt = elements.iterator();
				while (elemIt.hasNext()) {
					Object elem = elemIt.next();
					objs.add(elem);
				}
			}
		}
		return objs;
	}
	/** Get all instances from population */
	public List getAllElements() {
		List res = new ArrayList();
		Iterator i = population.keySet().iterator();
		while (i.hasNext()) {
			String key = (String)i.next();
			res.addAll((Collection)population.get(key));
		}
		return res;
	}
	/** Get the entire population */
	public Map getPopulation() {
		return population;
	}

	//--- FACTORIES ---
	/** Get a specific factory */
	public javaModel.JavaModelFactory getFactory(String fullClassName) {
		javaModel.JavaModelFactory factory = null;
		try {
			factory = (javaModel.JavaModelFactory)factories.get(fullClassName);
		} catch (Exception e) {
			log.reportMessage("Error: Missing factory for '"+fullClassName+"' class");
		}
		return factory;
	}
	/** Get the all factories */
	public Map getFactories() {
		return factories;
	}

	//--- BROWSER ---
	/** Get a description using a JTree */
	public DefaultMutableTreeNode toJTree() {
		//--- Creat the JTree visitor ---
		JavaModelJTreeVisitor jtreeVisitor = new JavaModelJTreeVisitor$Class();
		//--- Init root ---
		DefaultMutableTreeNode root = new DefaultMutableTreeNode("Repository", true);
		DefaultMutableTreeNode factoriesNode = new DefaultMutableTreeNode("Lifecycle", true);
		DefaultMutableTreeNode elementsNode = new DefaultMutableTreeNode("Elements", true);
		root.add(factoriesNode);
		root.add(elementsNode);
		//--- Add every factory ---
		Set factoryNames = factories.keySet();
		Iterator i = factoryNames.iterator();
		while (i.hasNext()) {
			String factoryName = (String)i.next();
			JavaModelFactory factory = (JavaModelFactory)factories.get(factoryName);
			DefaultMutableTreeNode factoryNode = (DefaultMutableTreeNode)factory.accept(jtreeVisitor, new Object());
			factoriesNode.add(factoryNode);
		}
		//--- Add every element ---
		Set elemNames = population.keySet();
		Iterator j = elemNames.iterator();
		while (j.hasNext()) {
			String elemName = (String)j.next();
			//--- Add a node for each class ---
			List elements = (List)population.get(elemName);
			if (elements.size() != 0) {
				DefaultMutableTreeNode elemNode = new DefaultMutableTreeNode("Instances of "+elemName, true);
				Iterator elementIt = elements.iterator();
				while (elementIt.hasNext()) {
					JavaModelElement element = (JavaModelElement)elementIt.next();
					//--- Add a node for each instance ---
					Set visitedElements = new LinkedHashSet();
					visitedElements.add(element);
					DefaultMutableTreeNode instanceNode = (DefaultMutableTreeNode)element.accept(jtreeVisitor, visitedElements);
					elemNode.add(instanceNode);
				}
				elementsNode.add(elemNode);
			}
		}
		return root;
	}

	/** Save the content into an XMI file */
	public void saveXMI(String fileName) {
		//--- Create an XMI file ---
		if (!fileName.toLowerCase().endsWith(".xml")) fileName += ".xml";
		XMIFile xmiFile = new XMIFile(fileName);
		//--- Create an XMI vistor ---
		JavaModelXMIVisitor xmiVisitor = new JavaModelXMIVisitor$Class();
		//--- Create an empty (reference, xmiObject) table  ---
		Map mapRefToXMI = new IdentityHashMap();
		//--- Create the top objects container ---
		Collection topObjs = xmiFile.getTopObjects();
		//--- For each factory ---
		Set factoryNames = factories.keySet();
		Iterator i = factoryNames.iterator();
		while (i.hasNext()) {
			String elemName = (String)i.next();
			JavaModelFactory factory = (JavaModelFactory)factories.get(elemName);
			//--- Create the factory ---
			XMIObject xmifactory = (XMIObject)factory.accept(xmiVisitor, mapRefToXMI);
			//--- Add factory to top objects ---
			//--- Compute all the instances created by the factory ---
			List elements = (List)population.get(elemName);
			if (elements == null) continue;
			Iterator j = elements.iterator();
			while (j.hasNext()) {
				JavaModelElement element = (JavaModelElement)j.next();
				//--- Create the XMI element ---
				XMIObject xmiElement = (XMIObject)element.accept(xmiVisitor, mapRefToXMI);
				//--- Add the element to top objects ---
				topObjs.add(xmiElement);
			}
		}
		try {
			//--- Register the AdapterFactory into XMI framework ---
			AdapterFactoryRegister.registerAdapterFactory(new JavaModelFactoryAdapter$Class(this, log));
			//--- Save the elements ---
			IXMIWriter writer = new XMIWriter();
			writer.write(xmiFile, fileName, log);
		} catch (Exception e) {
			log.reportMessage(""+e);
		}
	}
	/** Create a new repository from an XMI file */
	public uk.ac.kent.cs.kmf.common.Repository loadXMI(String fileName) {
		try {
			//--- Create a repository ---
			JavaModelRepository rep = new JavaModelRepository$Class();
			rep.setLog(log);
			//--- Register the AdapterFactory into XMI framework ---
			AdapterFactoryRegister.registerAdapterFactory(new JavaModelFactoryAdapter$Class(rep, log));
			//--- Build the elements ---
			XMIFile xmiFile = (new XMIReader()).read(fileName, log);
			return rep;
		} catch (Exception e) {
			log.reportMessage(""+e);
			return null;
		}
	}

	/** Get a HUTN description of the repository */
	public String toHUTN() {
		//--- Create the HUTN visitor ---
		JavaModelHUTNVisitor hutnVisitor = new JavaModelHUTNVisitor$Class();
		//--- Add every factory ---
		String buffer = new String();
		buffer += "JavaModelRepository {\n";
		buffer += "factories\n";
		Set factoryNames = factories.keySet();
		Iterator factoryIt = factoryNames.iterator();
		while (factoryIt.hasNext()) {
			String factoryName = (String)factoryIt.next();
			buffer += "  "+factoryName+"\n";
		}
		buffer += "\n";
		//--- Add every element ---
		buffer += "Elements\n";
		Set elemNames = population.keySet();
		Iterator elemIt = elemNames.iterator();
		while (elemIt.hasNext()) {
			String elemName = (String)elemIt.next();
			buffer += "Instances of "+elemName+"\n";
			List elements = (List)population.get(elemName);
			Iterator elementIt = elements.iterator();
			while (elementIt.hasNext()) {
				JavaModelElement element = (JavaModelElement)elementIt.next();
				buffer += element.accept(hutnVisitor, new Object());
			}
		}
		buffer += "}\n";
		log.reportMessage(buffer);
		return buffer;
	}
	/** Save the content into a HUTN file */
	public void saveHUTN(String fileName) {
		//--- Open the HUTN file ---
		if (!fileName.toLowerCase().endsWith(".hutn")) fileName += ".hutn";
		PrintWriter out;
		try {
			out = new PrintWriter(new FileWriter(new File(fileName)), true);
		} catch (Exception e) {
			log.reportMessage(""+e);
			return;
		}
		//--- Create the HUTN visitor ---
		JavaModelHUTNVisitor hutnVisitor = new JavaModelHUTNVisitor$Class();
		//--- Add every factory ---
		out.println("JavaModelRepository {");
		out.println("factories");
		Set factoryNames = factories.keySet();
		Iterator factoryIt = factoryNames.iterator();
		while (factoryIt.hasNext()) {
			String factoryName = (String)factoryIt.next();
			out.println("  "+factoryName);
		}
		out.println();
		//--- Add every element ---
		out.println("Elements");
		Set elemNames = population.keySet();
		Iterator elemIt = elemNames.iterator();
		while (elemIt.hasNext()) {
			String elemName = (String)elemIt.next();
			out.println("Instances of "+elemName);
			List elements = (List)population.get(elemName);
			Iterator elementIt = elements.iterator();
			while (elementIt.hasNext()) {
				JavaModelElement element = (JavaModelElement)elementIt.next();
				out.println(element.accept(hutnVisitor, new Object()));
			}
		}
		out.println("}");
		out.close();
	}
	/** Create a new repository from an HUTN file */
	public JavaModelRepository loadHUTN(String fileName) {
		try {
			//--- Create a repository ---
			JavaModelRepository rep = new JavaModelRepository$Class();
			return rep;
		} catch (Exception e) {
			log.reportMessage(""+e);
			return null;
		}
	}
	/** Add a factory */
	public void registerFactory(String fullClassName, JavaModelFactory factory) {
		if (!factories.containsKey(fullClassName)) {
			log.reportMessage("Factory for '"+fullClassName+"' was replaced");
		}
		factories.put(fullClassName, factory);
	}
	/** The factories */
	protected Hashtable factories = new Hashtable();

}
