/**
 *
 *  Class OperationAS.java
 *
 *  Generated by KMFStudio at 11 June 2003 13:46:49
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.syntax.ast.contexts;

import java.util.List;

import uk.ac.kent.cs.ocl20.syntax.SyntaxElement;

public interface OperationAS
extends
    SyntaxElement
{

	/** Get the 'pathName' from 'OperationAS' */
	public List getPathName();
	/** Set the 'pathName' from 'OperationAS' */
	public void setPathName(List pathName);

	/** Get the 'name' from 'OperationAS' */
	public String getName();
	/** Set the 'name' from 'OperationAS' */
	public void setName(String name);

	/** Get the 'type' from 'OperationAS' */
	public uk.ac.kent.cs.ocl20.syntax.ast.types.TypeAS getType();
	/** Set the 'type' from 'OperationAS' */
	public void setType(uk.ac.kent.cs.ocl20.syntax.ast.types.TypeAS type);

	/** Get the 'parameters' from 'OperationAS' */
	public List getParameters();
	/** Set the 'parameters' from 'OperationAS' */
	public void setParameters(List parameters);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
