/**
 *
 *  Class OperationContextDeclAS$Class.java
 *
 *  Generated by KMFStudio at 11 June 2003 13:46:49
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.syntax.ast.contexts;

import java.util.List;
import java.util.Vector;

import uk.ac.kent.cs.ocl20.syntax.SyntaxVisitable;
import uk.ac.kent.cs.ocl20.syntax.SyntaxVisitor;

public class OperationContextDeclAS$Class
extends
	ContextDeclarationAS$Class
implements
	OperationContextDeclAS,
    SyntaxVisitable
{
	/** Default constructor */
	public OperationContextDeclAS$Class() {
		//--- Set property 'constraints' from 'ContextDeclarationAS' ---
		this.constraints = new Vector();
		//--- Set property 'operation' from 'OperationContextDeclAS' ---
		this.operation = null;
	}


	/** Property 'operation' from 'OperationContextDeclAS' */
	protected OperationAS operation;
	/** Get property 'operation' from 'OperationContextDeclAS' */
	public OperationAS getOperation() {
		return operation;
	}
	/** Set property 'operation' from 'OperationContextDeclAS' */
	public void setOperation(OperationAS operation) { 
		this.operation = operation;
	}

	/** Get the location */
	protected Object location;
	public Object getLocation() {
		return location;
	}
	/** Set the location */
	public void setLocation(Object location) {
		this.location = location;
	}
	
	/** Override toString */
	public String toString() {
		String strId = "ast.contexts.OperationContextDeclAS";
		String name = null;
		try {
			java.lang.Class cls = this.getClass();
			java.lang.reflect.Method method = cls.getMethod("getName", new java.lang.Class[] {});
			name = (String) method.invoke(this, new Object[] {});
			if (name != null && name.length()==0) name = null;
		} catch (Exception e) {
		}
		if (name == null)
			return strId;
		else
			return strId+" '"+name+"'";
	}

	/** Accept 'uk.ac.kent.cs.ocl20.syntax.ast.contexts.OperationContextDeclAS$Visitor' */
	public Object accept(SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}

	/** Clone the object */
	public Object clone() {
		OperationContextDeclAS$Class obj = new OperationContextDeclAS$Class();
		obj.constraints = constraints==null ? null : (List)((Vector)this.constraints).clone();
		obj.operation = operation==null ? null : this.operation;
		return obj;
	}
}
