/**
 *
 *  Class PackageECA$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:35
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.ModelManagement;

public class PackageECA$Class
implements
	PackageECA,
    edoc.EdocVisitable
{
	/** Default constructor */
	public PackageECA$Class() {
		//--- Set property 'name' from 'PackageContent' ---
		this.name = null;
		//--- Set property 'namespace_' from 'PackageContent' ---
		this.namespace_ = null;
		//--- Set property 'elementImport' from 'PackageContent' ---
		this.elementImport = new java.util.LinkedHashSet();
		//--- Set property 'ownedElement' from 'PackageECA' ---
		this.ownedElement = new java.util.LinkedHashSet();
	}
	/** Specialized constructor */
	public PackageECA$Class(String name) {
		//--- Set property 'name' from 'PackageContent' ---
		this.name = name;
		//--- Set property 'namespace_' from 'PackageContent' ---
		this.namespace_ = null;
		//--- Set property 'elementImport' from 'PackageContent' ---
		this.elementImport = new java.util.LinkedHashSet();
		//--- Set property 'ownedElement' from 'PackageECA' ---
		this.ownedElement = new java.util.LinkedHashSet();
	}


	/** Property 'name' from 'PackageContent' */
	protected String name;
	/** Get property 'name' from 'PackageContent' */
		public String getName() {
		return name;
	}
	/** Set property 'name' from 'PackageContent' */
		public void setName(String name) {
		this.name = name;
	}

	/** Property 'namespace_' from 'PackageContent' */
	protected PackageECA namespace_;
	/** Get property 'namespace_' from 'PackageContent' */
	public PackageECA getNamespace_() {
		return namespace_;
	}
	/** Set property 'namespace_' from 'PackageContent' */
	public void setNamespace_(PackageECA namespace_) { 
		this.namespace_ = namespace_;
	}

	/** Property 'elementImport' from 'PackageContent' */
	protected java.util.Set elementImport;
	/** Get property 'elementImport' from 'PackageContent' */
	public java.util.Set getElementImport() {
		return elementImport;
	}
	/** Set property 'elementImport' from 'PackageContent' */
	public void setElementImport(java.util.Set elementImport) { 
		this.elementImport = elementImport;
	}

	/** Property 'ownedElement' from 'PackageECA' */
	protected java.util.Set ownedElement;
	/** Get property 'ownedElement' from 'PackageECA' */
	public java.util.Set getOwnedElement() {
		return ownedElement;
	}
	/** Set property 'ownedElement' from 'PackageECA' */
	public void setOwnedElement(java.util.Set ownedElement) { 
		this.ownedElement = ownedElement;
	}

	/** The id */
	protected String id;
	/** Get the id */
	public String getId() {
		return id;
	}
	/** Set the id */
	public void setId(String id) {
		this.id = id;
	}

	/** Override toString */
	public String toString() {
		String strId = "edoc.ECA.ModelManagement.PackageECA";
		String name = null;
		try {
			java.lang.Class cls = this.getClass();
			java.lang.reflect.Method method = cls.getMethod("getName", new java.lang.Class[] {});
			name = (String) method.invoke(this, new Object[] {});
			if (name != null && name.length()==0) name = null;
		} catch (Exception e) {
		}
		if (name == null)
			return strId+" 'id-"+getId()+"'";
		else
			return strId+" '"+name+"-"+getId()+"'";
	}

	/** Delete the object */
	public void delete() {
		if (namespace_ != null)
			this.namespace_.getOwnedElement().remove(this);
		java.util.Iterator elementImportIt = this.elementImport.iterator();
		while (elementImportIt.hasNext()) {
			edoc.ECA.ModelManagement.ElementImport elementImportObj = (edoc.ECA.ModelManagement.ElementImport)elementImportIt.next();
			if (elementImportObj != null)
				elementImportObj.setModelElement(null);
		}
		java.util.Iterator ownedElementIt = this.ownedElement.iterator();
		while (ownedElementIt.hasNext()) {
			edoc.ECA.ModelManagement.PackageContent ownedElementObj = (edoc.ECA.ModelManagement.PackageContent)ownedElementIt.next();
			if (ownedElementObj != null)
				ownedElementObj.setNamespace_(null);
		}
	}

	/** Clone the object */
	public Object clone() {
		PackageECA$Class obj = new PackageECA$Class();
		obj.name = name==null ? null : this.name;
		obj.namespace_ = namespace_==null ? null : this.namespace_;
		obj.elementImport = elementImport==null ? null : (java.util.Set)((java.util.LinkedHashSet)this.elementImport).clone();
		obj.ownedElement = ownedElement==null ? null : (java.util.Set)((java.util.LinkedHashSet)this.ownedElement).clone();
		return obj;
	}

	/** Accept 'edoc.ECA.ModelManagement.PackageECAVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
