/**
 *
 *  Class Abstraction.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core;

public interface Abstraction
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlElement,
    Dependency,
    Relationship,
    ModelElement,
    Element
{

	/** Get the 'mapping' from 'Abstraction' */
	public uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MappingExpression getMapping();
	/** Set the 'mapping' from 'Abstraction' */
	public void setMapping(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MappingExpression mapping);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
