/**
 *
 *  Class Binding.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core;

public interface Binding
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlElement,
    Dependency,
    Relationship,
    ModelElement,
    Element
{

	/** Get the 'argument' from 'Binding' */
	public java.util.Set getArgument();
	/** Set the 'argument' from 'Binding' */
	public void setArgument(java.util.Set argument);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
