/**
 *
 *  Class Class_.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core;

public interface Class_
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlElement,
    Classifier,
    GeneralizableElement,
    Namespace,
    ModelElement,
    Element
{

	/** Get the 'isActive' from 'Class_' */
	public Boolean getIsActive();
	/** Set the 'isActive' from 'Class_' */
	public void setIsActive(Boolean isActive);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
