/**
 *
 *  Class Component.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core;

public interface Component
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlElement,
    Classifier,
    GeneralizableElement,
    Namespace,
    ModelElement,
    Element
{

	/** Get the 'deploymentLocation' from 'Component' */
	public java.util.Set getDeploymentLocation();
	/** Set the 'deploymentLocation' from 'Component' */
	public void setDeploymentLocation(java.util.Set deploymentLocation);

	/** Get the 'resident' from 'Component' */
	public java.util.Set getResident();
	/** Set the 'resident' from 'Component' */
	public void setResident(java.util.Set resident);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
