/**
 *
 *  Class Dependency.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core;

public interface Dependency
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlElement,
    Relationship,
    ModelElement,
    Element
{

	/** Get the 'client' from 'Dependency' */
	public java.util.Set getClient();
	/** Set the 'client' from 'Dependency' */
	public void setClient(java.util.Set client);

	/** Get the 'supplier' from 'Dependency' */
	public java.util.Set getSupplier();
	/** Set the 'supplier' from 'Dependency' */
	public void setSupplier(java.util.Set supplier);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
