/**
 *
 *  Class Enumeration_$Factory$Class.java
 *
 *  Generated by KMFStudio at 29 July 2003 10:22:55
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core;

import uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory$Class;
import uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlVisitor;
import uk.ac.ukc.cs.kmf.kmfstudio.uml.repository.UmlRepository;

public class Enumeration_$Factory$Class
	extends UmlFactory$Class
	implements Enumeration_$Factory
{
	/** Default factory constructor */
	public Enumeration_$Factory$Class() {
	}
	public Enumeration_$Factory$Class(UmlRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Enumeration_ obj = new Enumeration_$Class();
		repository.addElement("uml.Foundation.Core.Enumeration_", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(Boolean isRoot, Boolean isLeaf, Boolean isAbstract, uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Name name, uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.VisibilityKind visibility, Boolean isSpecification) {
		Enumeration_ obj = new Enumeration_$Class(isRoot, isLeaf, isAbstract, name, visibility, isSpecification);
		repository.addElement("uml.Foundation.Core.Enumeration_", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "Enumeration__Factory";
	}

	/** Accept 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Enumeration_$Visitor' */
	public Object accept(UmlVisitor v, Object data) {
		return v.visit(this, data);
	}
}
