/**
 *
 *  Class Generalization.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core;

public interface Generalization
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlElement,
    Relationship,
    ModelElement,
    Element
{

	/** Get the 'discriminator' from 'Generalization' */
	public uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Name getDiscriminator();
	/** Set the 'discriminator' from 'Generalization' */
	public void setDiscriminator(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Name discriminator);

	/** Get the 'child' from 'Generalization' */
	public GeneralizableElement getChild();
	/** Set the 'child' from 'Generalization' */
	public void setChild(GeneralizableElement child);

	/** Get the 'parent' from 'Generalization' */
	public GeneralizableElement getParent();
	/** Set the 'parent' from 'Generalization' */
	public void setParent(GeneralizableElement parent);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
