/**
 *
 *  Class Node.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core;

public interface Node
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlElement,
    Classifier,
    GeneralizableElement,
    Namespace,
    ModelElement,
    Element
{

	/** Get the 'resident' from 'Node' */
	public java.util.Set getResident();
	/** Set the 'resident' from 'Node' */
	public void setResident(java.util.Set resident);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
