/**
 *
 *  Class Parameter.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core;

public interface Parameter
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlElement,
    ModelElement,
    Element
{

	/** Get the 'defaultValue' from 'Parameter' */
	public uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Expression getDefaultValue();
	/** Set the 'defaultValue' from 'Parameter' */
	public void setDefaultValue(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Expression defaultValue);

	/** Get the 'kind' from 'Parameter' */
	public uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ParameterDirectionKind getKind();
	/** Set the 'kind' from 'Parameter' */
	public void setKind(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ParameterDirectionKind kind);

	/** Get the 'type' from 'Parameter' */
	public Classifier getType();
	/** Set the 'type' from 'Parameter' */
	public void setType(Classifier type);

	/** Get the 'behavioralFeature' from 'Parameter' */
	public BehavioralFeature getBehavioralFeature();
	/** Set the 'behavioralFeature' from 'Parameter' */
	public void setBehavioralFeature(BehavioralFeature behavioralFeature);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
