/**
 *
 *  Class Signal.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core;

public interface Signal
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlElement,
    ModelElement,
    Element
{

	/** Get the 'sendAction' from 'Signal' */
	public java.util.Set getSendAction();
	/** Set the 'sendAction' from 'Signal' */
	public void setSendAction(java.util.Set sendAction);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
