/**
 *
 *  Class ActionFactory.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:46
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines;

public interface ActionFactory
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory
{
	/** Default builder */
	public Object build();
}
