/**
 *
 *  Class Pseudostate$Factory$Class.java
 *
 *  Generated by KMFStudio at 29 July 2003 10:22:57
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines;

import uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory$Class;
import uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlVisitor;
import uk.ac.ukc.cs.kmf.kmfstudio.uml.repository.UmlRepository;

public class Pseudostate$Factory$Class
	extends UmlFactory$Class
	implements Pseudostate$Factory
{
	/** Default factory constructor */
	public Pseudostate$Factory$Class() {
	}
	public Pseudostate$Factory$Class(UmlRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Pseudostate obj = new Pseudostate$Class();
		repository.addElement("uml.Behavioral_Elements.State_Machines.Pseudostate", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Name name, uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.VisibilityKind visibility, Boolean isSpecification, String kind) {
		Pseudostate obj = new Pseudostate$Class(name, visibility, isSpecification, kind);
		repository.addElement("uml.Behavioral_Elements.State_Machines.Pseudostate", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "Pseudostate_Factory";
	}

	/** Accept 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Pseudostate$Visitor' */
	public Object accept(UmlVisitor v, Object data) {
		return v.visit(this, data);
	}
}
