/**
 *
 *  Class CollectionTypeAS.java
 *
 *  Generated by KMFStudio at 11 June 2003 13:46:49
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.syntax.ast.types;

import uk.ac.kent.cs.ocl20.syntax.SyntaxElement;

public interface CollectionTypeAS
extends
    SyntaxElement,
    TypeAS
{

	/** Get the 'elementType' from 'CollectionTypeAS' */
	public TypeAS getElementType();
	/** Set the 'elementType' from 'CollectionTypeAS' */
	public void setElementType(TypeAS elementType);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
