/**
 *
 *  Class IterateExpAS.java
 *
 *  Generated by KMFStudio at 13 April 2004 12:05:02
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.ocl20.syntax.ast.expressions;

public interface IterateExpAS
extends
    uk.ac.ukc.cs.kmf.ocl20.syntax.SyntaxElement,
    LoopExpAS,
    OclExpressionAS
{

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
