/**
 *
 *  Class OclMessageExpAS.java
 *
 *  Generated by KMFStudio at 13 April 2004 12:05:02
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.ocl20.syntax.ast.expressions;

public interface OclMessageExpAS
extends
    uk.ac.ukc.cs.kmf.ocl20.syntax.SyntaxElement,
    OclExpressionAS
{

	/** Get the 'name' from 'OclMessageExpAS' */
	public String getName();
	/** Set the 'name' from 'OclMessageExpAS' */
	public void setName(String name);

	/** Get the 'kind' from 'OclMessageExpAS' */
	public OclMessageKindAS getKind();
	/** Set the 'kind' from 'OclMessageExpAS' */
	public void setKind(OclMessageKindAS kind);

	/** Get the 'target' from 'OclMessageExpAS' */
	public OclExpressionAS getTarget();
	/** Set the 'target' from 'OclMessageExpAS' */
	public void setTarget(OclExpressionAS target);

	/** Get the 'arguments' from 'OclMessageExpAS' */
	public java.util.List getArguments();
	/** Set the 'arguments' from 'OclMessageExpAS' */
	public void setArguments(java.util.List arguments);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
