/**
 *
 *  Class UmlFactory$Class.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:47
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml;

public class UmlFactory$Class
	implements UmlFactory
{
	/** Default constructor */
	public UmlFactory$Class() {
	}
	/** Specialized constructor */
	public UmlFactory$Class(uk.ac.ukc.cs.kmf.kmfstudio.uml.repository.UmlRepository repository) {
		this.repository = repository;
	}
	/** Build object */
	public Object build() {
		return null;
	}

	/** The id */
	private static int objId = 0;
	/** Reset the id */
	public static void resetId() {
		objId = 0;
	}
	/** Get a new id */
	public static String newId() {
		return ""+ ++objId;
	}

	/** The repository */
	protected uk.ac.ukc.cs.kmf.kmfstudio.uml.repository.UmlRepository repository;
	/** Get the repository */
	public uk.ac.ukc.cs.kmf.kmfstudio.uml.repository.UmlRepository getRepository() {
		return repository;
	}
	/** Set the repository */
	public void setRepository(uk.ac.ukc.cs.kmf.kmfstudio.uml.repository.UmlRepository repository) {
		this.repository = repository;
	}

	/** Override toString */
	public String toString() {
		return "UmlFactory";
	}

	/** Accept 'UmlVisitor' */
	public Object accept(UmlVisitor v, Object data) {
		return v.visit(this, data);
	}
}
