/**
 *
 *  Class UmlVisitor.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:47
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml;

public interface UmlVisitor {
	/** Visit 'uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.UnlimitedInteger' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.UnlimitedIntegerFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.UnlimitedInteger' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.UnlimitedInteger host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Time' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.TimeFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Time' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Time host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Expression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ExpressionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Expression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Expression host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Name' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.NameFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Name' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Name host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Multiplicity' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MultiplicityFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Multiplicity' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Multiplicity host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MultiplicityRange' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MultiplicityRangeFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MultiplicityRange' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MultiplicityRange host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.LocationReference' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.LocationReferenceFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.LocationReference' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.LocationReference host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MappingExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MappingExpressionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MappingExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MappingExpression host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Geometry' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.GeometryFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Geometry' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Geometry host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ActionExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ActionExpressionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ActionExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ActionExpression host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.BooleanExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.BooleanExpressionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.BooleanExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.BooleanExpression host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ProcedureExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ProcedureExpressionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ProcedureExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ProcedureExpression host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.TypeExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.TypeExpressionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.TypeExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.TypeExpression host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ArgListsExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ArgListsExpressionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ArgListsExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ArgListsExpression host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.IterationExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.IterationExpressionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.IterationExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.IterationExpression host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ObjectSetExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ObjectSetExpressionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ObjectSetExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ObjectSetExpression host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.TimeExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.TimeExpressionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.TimeExpression' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.TimeExpression host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ScopeKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ScopeKindFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ScopeKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ScopeKind host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MessageDirectionKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MessageDirectionKindFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MessageDirectionKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MessageDirectionKind host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.OrderingKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.OrderingKindFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.OrderingKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.OrderingKind host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ParameterDirectionKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ParameterDirectionKindFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ParameterDirectionKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ParameterDirectionKind host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.VisibilityKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.VisibilityKindFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.VisibilityKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.VisibilityKind host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.CallConcurrencyKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.CallConcurrencyKindFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.CallConcurrencyKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.CallConcurrencyKind host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.PseudostateKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.PseudostateKindFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.PseudostateKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.PseudostateKind host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.AggregationKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.AggregationKindFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.AggregationKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.AggregationKind host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ChangeabilityKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ChangeabilityKindFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ChangeabilityKind' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ChangeabilityKind host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.TaggedValue' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.TaggedValueFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.TaggedValue' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.TaggedValue host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.Stereotype' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.StereotypeFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.Stereotype' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.Stereotype host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.TagDefinition' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.TagDefinitionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.TagDefinition' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.TagDefinition host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.StringArray' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.StringArrayFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.StringArray' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.StringArray host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Parameter' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.ParameterFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Parameter' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Parameter host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Method' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.MethodFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Method' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Method host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Element' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.ElementFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Element' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Element host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Feature' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.FeatureFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Feature' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Feature host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.StructuralFeature' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.StructuralFeatureFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.StructuralFeature' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.StructuralFeature host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.BehavioralFeature' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.BehavioralFeatureFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.BehavioralFeature' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.BehavioralFeature host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Operation' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.OperationFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Operation' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Operation host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Attribute' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AttributeFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Attribute' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Attribute host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Relationship' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.RelationshipFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Relationship' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Relationship host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AssociationEnd' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AssociationEndFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AssociationEnd' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AssociationEnd host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Association' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AssociationFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Association' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Association host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Flow' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.FlowFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Flow' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Flow host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Generalization' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.GeneralizationFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Generalization' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Generalization host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Classifier' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.ClassifierFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Classifier' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Classifier host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Class_' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Class_Factory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Class_' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Class_ host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AssociationClass' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AssociationClassFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AssociationClass' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AssociationClass host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Dependency' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.DependencyFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Dependency' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Dependency host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Binding' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.BindingFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Binding' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Binding host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Usage' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.UsageFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Usage' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Usage host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Abstraction' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.AbstractionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Abstraction' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Abstraction host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Permission' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.PermissionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Permission' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Permission host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Interface' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.InterfaceFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Interface' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Interface host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.DataType' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.DataTypeFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.DataType' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.DataType host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Node' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.NodeFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Node' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Node host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Component' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.ComponentFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Component' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Component host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.GeneralizableElement' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.GeneralizableElementFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.GeneralizableElement' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.GeneralizableElement host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Constraint' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.ConstraintFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Constraint' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Constraint host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.ModelElement' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.ModelElementFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.ModelElement' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.ModelElement host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Namespace' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.NamespaceFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Namespace' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Namespace host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Comment' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.CommentFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Comment' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Comment host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.PresentationElement' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.PresentationElementFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.PresentationElement' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.PresentationElement host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Tie' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.TieFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Tie' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Tie host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.TemplateParameter' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.TemplateParameterFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.TemplateParameter' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.TemplateParameter host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Signal' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.SignalFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Signal' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Signal host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.CallAction' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.CallActionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.CallAction' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.CallAction host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.SendAction' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.SendActionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.SendAction' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.SendAction host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Primitive' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.PrimitiveFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Primitive' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Primitive host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Enumeration_' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Enumeration_Factory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Enumeration_' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.Enumeration_ host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.EnumLiteral' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.EnumLiteralFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.EnumLiteral' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Core.EnumLiteral host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.Package' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.PackageFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.Package' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.Package host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.Model' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.ModelFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.Model' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.Model host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.Subsystem' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.SubsystemFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.Subsystem' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Model_Management.Subsystem host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StateMachine' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StateMachineFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StateMachine' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StateMachine host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Guard' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.GuardFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Guard' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Guard host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Transition' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.TransitionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Transition' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Transition host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StateVertex' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StateVertexFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StateVertex' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StateVertex host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.State' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StateFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.State' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.State host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Action' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.ActionFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Action' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Action host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.SynchState' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.SynchStateFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.SynchState' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.SynchState host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Pseudostate' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.PseudostateFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Pseudostate' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Pseudostate host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StubState' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StubStateFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StubState' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.StubState host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Event' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.EventFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Event' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.Event host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.CallEvent' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.CallEventFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.CallEvent' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.CallEvent host, Object data);
	/** Visit factory for 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.CompositeState' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.CompositeStateFactory host, Object data);
	/** Visit class 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.CompositeState' */
	public Object visit(uk.ac.ukc.cs.kmf.kmfstudio.uml.Behavioral_Elements.State_Machines.CompositeState host, Object data);
}
