/**
 *
 *  Class ClassifierContextDeclASFactory$Class.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:43
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.contexts;

public class ClassifierContextDeclASFactory$Class
	extends ocl.syntax.SyntaxFactory$Class
	implements ClassifierContextDeclASFactory
{
	/** Default factory constructor */
	public ClassifierContextDeclASFactory$Class() {
	}
	public ClassifierContextDeclASFactory$Class(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		ClassifierContextDeclAS obj = new ClassifierContextDeclAS$Class();
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.contexts.ClassifierContextDeclAS", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(java.util.List pathName) {
		ClassifierContextDeclAS obj = new ClassifierContextDeclAS$Class(pathName);
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.contexts.ClassifierContextDeclAS", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ClassifierContextDeclASFactory";
	}

	/** Accept 'ocl.syntax.ast.contexts.ClassifierContextDeclASVisitor' */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
