/**
 *
 *  Class ContextDeclarationAS$Factory.java
 *
 *  Generated by KMFStudio at 25 November 2003 13:00:54
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.contexts;

public interface ContextDeclarationAS$Factory
extends
    ocl.syntax.SyntaxFactory
{
	/** Default builder */
	public Object build();
}
