/**
 *
 *  Class ContextDeclarationASFactory$Class.java
 *
 *  Generated by KMFStudio at 17 February 2004 14:38:43
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.contexts;

public class ContextDeclarationASFactory$Class
	extends ocl.syntax.SyntaxFactory$Class
	implements ContextDeclarationASFactory
{
	/** Default factory constructor */
	public ContextDeclarationASFactory$Class() {
	}
	public ContextDeclarationASFactory$Class(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		ContextDeclarationAS obj = new ContextDeclarationAS$Class();
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.contexts.ContextDeclarationAS", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ContextDeclarationASFactory";
	}

	/** Accept 'ocl.syntax.ast.contexts.ContextDeclarationASVisitor' */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
