/**
 *
 *  Class PropertyContextDeclAS$Factory$Class.java
 *
 *  Generated by KMFStudio at 25 November 2003 13:00:54
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ocl.syntax.ast.contexts;

public class PropertyContextDeclAS$Factory$Class
	extends ocl.syntax.SyntaxFactory$Class
	implements PropertyContextDeclAS$Factory
{
	/** Default factory constructor */
	public PropertyContextDeclAS$Factory$Class() {
	}
	public PropertyContextDeclAS$Factory$Class(ocl.syntax.repository.SyntaxRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		PropertyContextDeclAS obj = new PropertyContextDeclAS$Class();
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.contexts.PropertyContextDeclAS", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(java.util.List pathName, String name) {
		PropertyContextDeclAS obj = new PropertyContextDeclAS$Class(pathName, name);
		obj.setId(ocl.syntax.SyntaxFactory$Class.newId());
		repository.addElement("syntax.ast.contexts.PropertyContextDeclAS", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "PropertyContextDeclAS_Factory";
	}

	/** Accept 'ocl.syntax.ast.contexts.PropertyContextDeclAS$Visitor' */
	public Object accept(ocl.syntax.SyntaxVisitor v, Object data) {
		return v.visit(this, data);
	}
}
