/**
 *
 *  Class ConstraintAS.java
 *
 *  Generated by KMFStudio at 13 April 2004 12:05:02
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.ocl20.syntax.ast.contexts;

public interface ConstraintAS
extends
    uk.ac.ukc.cs.kmf.ocl20.syntax.SyntaxElement
{

	/** Get the 'name' from 'ConstraintAS' */
	public String getName();
	/** Set the 'name' from 'ConstraintAS' */
	public void setName(String name);

	/** Get the 'kind' from 'ConstraintAS' */
	public ConstraintKindAS getKind();
	/** Set the 'kind' from 'ConstraintAS' */
	public void setKind(ConstraintKindAS kind);

	/** Get the 'defOperation' from 'ConstraintAS' */
	public OperationAS getDefOperation();
	/** Set the 'defOperation' from 'ConstraintAS' */
	public void setDefOperation(OperationAS defOperation);

	/** Get the 'defVariable' from 'ConstraintAS' */
	public VariableDeclarationAS getDefVariable();
	/** Set the 'defVariable' from 'ConstraintAS' */
	public void setDefVariable(VariableDeclarationAS defVariable);

	/** Get the 'bodyExpression' from 'ConstraintAS' */
	public uk.ac.ukc.cs.kmf.ocl20.syntax.ast.expressions.OclExpressionAS getBodyExpression();
	/** Set the 'bodyExpression' from 'ConstraintAS' */
	public void setBodyExpression(uk.ac.ukc.cs.kmf.ocl20.syntax.ast.expressions.OclExpressionAS bodyExpression);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
