/**
 *
 *  Class ContextDeclarationAS.java
 *
 *  Generated by KMFStudio at 13 April 2004 12:05:02
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.ocl20.syntax.ast.contexts;

public interface ContextDeclarationAS
extends
    uk.ac.ukc.cs.kmf.ocl20.syntax.SyntaxElement
{

	/** Get the 'constraints' from 'ContextDeclarationAS' */
	public java.util.List getConstraints();
	/** Set the 'constraints' from 'ContextDeclarationAS' */
	public void setConstraints(java.util.List constraints);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
