/**
 *
 *  Class PropertyContextDeclAS.java
 *
 *  Generated by KMFStudio at 13 April 2004 12:05:02
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.ocl20.syntax.ast.contexts;

public interface PropertyContextDeclAS
extends
    uk.ac.ukc.cs.kmf.ocl20.syntax.SyntaxElement,
    ContextDeclarationAS
{

	/** Get the 'pathName' from 'PropertyContextDeclAS' */
	public java.util.List getPathName();
	/** Set the 'pathName' from 'PropertyContextDeclAS' */
	public void setPathName(java.util.List pathName);

	/** Get the 'name' from 'PropertyContextDeclAS' */
	public String getName();
	/** Set the 'name' from 'PropertyContextDeclAS' */
	public void setName(String name);

	/** Get the 'type' from 'PropertyContextDeclAS' */
	public uk.ac.ukc.cs.kmf.ocl20.syntax.ast.types.TypeAS getType();
	/** Set the 'type' from 'PropertyContextDeclAS' */
	public void setType(uk.ac.ukc.cs.kmf.ocl20.syntax.ast.types.TypeAS type);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
