/**
 *
 *  Class SdElement.java
 *
 *  Generated by KMFStudio at 18 February 2004 20:38:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd;

public interface SdElement
	extends SdVisitable
{
	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Delete */
	public void delete();
	/** Override toString */
	public String toString();
}
