/**
 *
 *  Class JavaModelFactory$Class.java
 *
 *  Generated by KMFStudio at 22 February 2004 15:13:03
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package javaModel;

public class JavaModelFactory$Class
	implements JavaModelFactory
{
	/** Default constructor */
	public JavaModelFactory$Class() {
	}
	/** Specialized constructor */
	public JavaModelFactory$Class(javaModel.repository.JavaModelRepository repository) {
		this.repository = repository;
	}
	/** Build object */
	public Object build() {
		return null;
	}

	/** The id */
	private static int objId = 0;
	/** Reset the id */
	public static void resetId() {
		objId = 0;
	}
	/** Get a new id */
	public static String newId() {
		return ""+ ++objId;
	}

	/** The repository */
	protected javaModel.repository.JavaModelRepository repository;
	/** Get the repository */
	public javaModel.repository.JavaModelRepository getRepository() {
		return repository;
	}
	/** Set the repository */
	public void setRepository(javaModel.repository.JavaModelRepository repository) {
		this.repository = repository;
	}

	/** Override toString */
	public String toString() {
		return "JavaModelFactory";
	}

	/** Accept 'JavaModelVisitor' */
	public Object accept(JavaModelVisitor v, Object data) {
		return v.visit(this, data);
	}
}
