/**
 *
 *  Class JavaInterface.java
 *
 *  Generated by KMFStudio at 22 February 2004 15:13:02
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package javaModel;

public interface JavaInterface
extends
    javaModel.JavaModelElement,
    JavaClassifier,
    JavaPackageElement,
    JavaElement
{

	/** Get the 'implementedBy' from 'JavaInterface' */
	public java.util.Set getImplementedBy();
	/** Set the 'implementedBy' from 'JavaInterface' */
	public void setImplementedBy(java.util.Set implementedBy);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
