/**
 *
 *  Class JavaModelFactory.java
 *
 *  Generated by KMFStudio at 22 February 2004 15:13:03
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package javaModel;

public interface JavaModelFactory
	extends JavaModelVisitable
{
	/** Build an object */
	public Object build();

	/** Get the repository */
	public javaModel.repository.JavaModelRepository getRepository();
	/** Set the repository */
	public void setRepository(javaModel.repository.JavaModelRepository repository);

	/** Override toString */
	public String toString();
}
