/**
 *
 *  Class JavaMethodFactory$Class.java
 *
 *  Generated by KMFStudio at 22 February 2004 15:13:03
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package javaModel;

public class JavaMethodFactory$Class
	extends javaModel.JavaModelFactory$Class
	implements JavaMethodFactory
{
	/** Default factory constructor */
	public JavaMethodFactory$Class() {
	}
	public JavaMethodFactory$Class(javaModel.repository.JavaModelRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		JavaMethod obj = new JavaMethod$Class();
		obj.setId(javaModel.JavaModelFactory$Class.newId());
		repository.addElement("javaModel.JavaMethod", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name, Boolean isAbstract, Boolean isNative, Boolean isSynchronized, Boolean isFinal, Boolean isConstructor, Boolean isStatic, String body) {
		JavaMethod obj = new JavaMethod$Class(name, isAbstract, isNative, isSynchronized, isFinal, isConstructor, isStatic, body);
		obj.setId(javaModel.JavaModelFactory$Class.newId());
		repository.addElement("javaModel.JavaMethod", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "JavaMethodFactory";
	}

	/** Accept 'javaModel.JavaMethodVisitor' */
	public Object accept(javaModel.JavaModelVisitor v, Object data) {
		return v.visit(this, data);
	}
}
