/**
 *
 *  Class JavaPackageElementFactory$Class.java
 *
 *  Generated by KMFStudio at 22 February 2004 15:13:03
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package javaModel;

public class JavaPackageElementFactory$Class
	extends javaModel.JavaModelFactory$Class
	implements JavaPackageElementFactory
{
	/** Default factory constructor */
	public JavaPackageElementFactory$Class() {
	}
	public JavaPackageElementFactory$Class(javaModel.repository.JavaModelRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		JavaPackageElement obj = new JavaPackageElement$Class();
		obj.setId(javaModel.JavaModelFactory$Class.newId());
		repository.addElement("javaModel.JavaPackageElement", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		JavaPackageElement obj = new JavaPackageElement$Class(name);
		obj.setId(javaModel.JavaModelFactory$Class.newId());
		repository.addElement("javaModel.JavaPackageElement", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "JavaPackageElementFactory";
	}

	/** Accept 'javaModel.JavaPackageElementVisitor' */
	public Object accept(javaModel.JavaModelVisitor v, Object data) {
		return v.visit(this, data);
	}
}
