/**
 *
 *  Class JavaElement.java
 *
 *  Generated by KMFStudio at 22 February 2004 15:13:02
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package javaModel;

public interface JavaElement
extends
    javaModel.JavaModelElement
{

	/** Get the 'name' from 'JavaElement' */
	public String getName();
	/** Set the 'name' from 'JavaElement' */
	public void setName(String name);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
