/**
 *
 *  Class JavaModelVisitor.java
 *
 *  Generated by KMFStudio at 22 February 2004 15:13:03
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package javaModel;

public class JavaModelVisitor$Class {
	/** Visit 'javaModel.JavaModelFactory' */
	public Object visit(javaModel.JavaModelFactory host, Object data) {
		return host;
	}
	/** Visit factory for 'javaModel.JavaClass' */
	public Object visit(javaModel.JavaClassFactory host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.JavaClass' */
	public Object visit(javaModel.JavaClass host, Object data) {
		return host;
	}
	/** Visit factory for 'javaModel.JavaField' */
	public Object visit(javaModel.JavaFieldFactory host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.JavaField' */
	public Object visit(javaModel.JavaField host, Object data) {
		return host;
	}
	/** Visit factory for 'javaModel.JavaMethod' */
	public Object visit(javaModel.JavaMethodFactory host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.JavaMethod' */
	public Object visit(javaModel.JavaMethod host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.JavaElement' */
	public Object visit(javaModel.JavaElement host, Object data) {
		return host;
	}
	/** Visit factory for 'javaModel.JavaPackage' */
	public Object visit(javaModel.JavaPackageFactory host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.JavaPackage' */
	public Object visit(javaModel.JavaPackage host, Object data) {
		return host;
	}
	/** Visit factory for 'javaModel.JavaParameter' */
	public Object visit(javaModel.JavaParameterFactory host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.JavaParameter' */
	public Object visit(javaModel.JavaParameter host, Object data) {
		return host;
	}
	/** Visit factory for 'javaModel.JavaPackageElement' */
	public Object visit(javaModel.JavaPackageElementFactory host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.JavaPackageElement' */
	public Object visit(javaModel.JavaPackageElement host, Object data) {
		return host;
	}
	/** Visit factory for 'javaModel.JavaInterface' */
	public Object visit(javaModel.JavaInterfaceFactory host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.JavaInterface' */
	public Object visit(javaModel.JavaInterface host, Object data) {
		return host;
	}
	/** Visit factory for 'javaModel.JavaClassifier' */
	public Object visit(javaModel.JavaClassifierFactory host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.JavaClassifier' */
	public Object visit(javaModel.JavaClassifier host, Object data) {
		return host;
	}
	/** Visit factory for 'javaModel.DataType' */
	public Object visit(javaModel.DataTypeFactory host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.DataType' */
	public Object visit(javaModel.DataType host, Object data) {
		return host;
	}
	/** Visit factory for 'javaModel.DataKind' */
	public Object visit(javaModel.DataKindFactory host, Object data) {
		return host;
	}
	/** Visit class 'javaModel.DataKind' */
	public Object visit(javaModel.DataKind host, Object data) {
		return host;
	}
}
