/**
 *
 *  Class CollectionRangeAS.java
 *
 *  Generated by KMFStudio at 11 June 2003 13:46:49
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.syntax.ast.expressions;

import uk.ac.kent.cs.ocl20.syntax.SyntaxElement;

public interface CollectionRangeAS
extends
    SyntaxElement,
    CollectionLiteralPartAS
{

	/** Get the 'last' from 'CollectionRangeAS' */
	public OclExpressionAS getLast();
	/** Set the 'last' from 'CollectionRangeAS' */
	public void setLast(OclExpressionAS last);

	/** Get the 'first' from 'CollectionRangeAS' */
	public OclExpressionAS getFirst();
	/** Set the 'first' from 'CollectionRangeAS' */
	public void setFirst(OclExpressionAS first);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
