/**
 *
 *  Class CollectionItemAS.java
 *
 *  Generated by KMFStudio at 11 June 2003 13:46:50
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.syntax.ast.expressions;

import uk.ac.kent.cs.ocl20.syntax.SyntaxElement;

public interface CollectionItemAS
extends
    SyntaxElement,
    CollectionLiteralPartAS
{

	/** Get the 'item' from 'CollectionItemAS' */
	public OclExpressionAS getItem();
	/** Set the 'item' from 'CollectionItemAS' */
	public void setItem(OclExpressionAS item);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
