/**
 *
 *  Class DotSelectionExpAS.java
 *
 *  Generated by KMFStudio at 11 June 2003 13:46:50
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.syntax.ast.expressions;

import uk.ac.kent.cs.ocl20.syntax.SyntaxElement;

public interface DotSelectionExpAS
extends
    SyntaxElement,
    SelectionExpAS,
    OclExpressionAS
{

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
