/**
 *
 *  Class SelectionExpAS.java
 *
 *  Generated by KMFStudio at 11 June 2003 13:46:49
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.syntax.ast.expressions;

import uk.ac.kent.cs.ocl20.syntax.SyntaxElement;

public interface SelectionExpAS
extends
    SyntaxElement,
    OclExpressionAS
{

	/** Get the 'name' from 'SelectionExpAS' */
	public String getName();
	/** Set the 'name' from 'SelectionExpAS' */
	public void setName(String name);

	/** Get the 'source' from 'SelectionExpAS' */
	public OclExpressionAS getSource();
	/** Set the 'source' from 'SelectionExpAS' */
	public void setSource(OclExpressionAS source);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
