/**
 *
 *  Class StringLiteralExpAS.java
 *
 *  Generated by KMFStudio at 11 June 2003 13:46:49
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.syntax.ast.expressions;

import uk.ac.kent.cs.ocl20.syntax.SyntaxElement;

public interface StringLiteralExpAS
extends
    SyntaxElement,
    PrimitiveLiteralExpAS,
    LiteralExpAS,
    PrimaryExpAS,
    OclExpressionAS
{

	/** Get the 'value' from 'StringLiteralExpAS' */
	public String getValue();
	/** Set the 'value' from 'StringLiteralExpAS' */
	public void setValue(String value);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
