/**
 *
 *  Class TupleLiteralExpAS.java
 *
 *  Generated by KMFStudio at 11 June 2003 13:46:49
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.syntax.ast.expressions;

import java.util.List;

import uk.ac.kent.cs.ocl20.syntax.SyntaxElement;

public interface TupleLiteralExpAS
extends
    SyntaxElement,
    LiteralExpAS,
    PrimaryExpAS,
    OclExpressionAS
{

	/** Get the 'tupleParts' from 'TupleLiteralExpAS' */
	public List getTupleParts();
	/** Set the 'tupleParts' from 'TupleLiteralExpAS' */
	public void setTupleParts(List tupleParts);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
