/**
 *
 *  Class BindingFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.wsdl;

public class BindingFactory$Class
	extends ws.WsFactory$Class
	implements BindingFactory
{
	/** Default factory constructor */
	public BindingFactory$Class() {
	}
	public BindingFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Binding obj = new Binding$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.wsdl.Binding", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		Binding obj = new Binding$Class(name);
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.wsdl.Binding", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "BindingFactory";
	}

	/** Accept 'ws.wsdl.BindingVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
