/**
 *
 *  Class ExtensibleElementFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.wsdl;

public class ExtensibleElementFactory$Class
	extends ws.WsFactory$Class
	implements ExtensibleElementFactory
{
	/** Default factory constructor */
	public ExtensibleElementFactory$Class() {
	}
	public ExtensibleElementFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		ExtensibleElement obj = new ExtensibleElement$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.wsdl.ExtensibleElement", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ExtensibleElementFactory";
	}

	/** Accept 'ws.wsdl.ExtensibleElementVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
