/**
 *
 *  Class Input.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.wsdl;

public interface Input
extends
    ws.WsElement
{

	/** Get the 'name' from 'Input' */
	public String getName();
	/** Set the 'name' from 'Input' */
	public void setName(String name);

	/** Get the 'message' from 'Input' */
	public Message getMessage();
	/** Set the 'message' from 'Input' */
	public void setMessage(Message message);

	/** Get the 'operation' from 'Input' */
	public Operation getOperation();
	/** Set the 'operation' from 'Input' */
	public void setOperation(Operation operation);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
