/**
 *
 *  Class Operation.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.wsdl;

public interface Operation
extends
    ws.WsElement,
    WSDLElement
{

	/** Get the 'name' from 'Operation' */
	public String getName();
	/** Set the 'name' from 'Operation' */
	public void setName(String name);

	/** Get the 'partnerActivity' from 'Operation' */
	public ws.bpel.PartnerActivity getPartnerActivity();
	/** Set the 'partnerActivity' from 'Operation' */
	public void setPartnerActivity(ws.bpel.PartnerActivity partnerActivity);

	/** Get the 'input' from 'Operation' */
	public Input getInput();
	/** Set the 'input' from 'Operation' */
	public void setInput(Input input);

	/** Get the 'output' from 'Operation' */
	public Output getOutput();
	/** Set the 'output' from 'Operation' */
	public void setOutput(Output output);

	/** Get the 'faults' from 'Operation' */
	public java.util.List getFaults();
	/** Set the 'faults' from 'Operation' */
	public void setFaults(java.util.List faults);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
