/**
 *
 *  Class Part$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.wsdl;

public class Part$Class
implements
	Part,
    ws.WsVisitable
{
	/** Default constructor */
	public Part$Class() {
		//--- Set property 'name' from 'Part' ---
		this.name = null;
		//--- Set property 'element' from 'Part' ---
		this.element = null;
		//--- Set property 'type' from 'Part' ---
		this.type = null;
		//--- Set property 'message' from 'Part' ---
		this.message = null;
	}
	/** Specialized constructor */
	public Part$Class(String name, String element, ws.xsd.Type type) {
		//--- Set property 'name' from 'Part' ---
		this.name = name;
		//--- Set property 'element' from 'Part' ---
		this.element = element;
		//--- Set property 'type' from 'Part' ---
		this.type = type;
		//--- Set property 'message' from 'Part' ---
		this.message = null;
	}


	/** Property 'name' from 'Part' */
	protected String name;
	/** Get property 'name' from 'Part' */
		public String getName() {
		return name;
	}
	/** Set property 'name' from 'Part' */
		public void setName(String name) {
		this.name = name;
	}

	/** Property 'element' from 'Part' */
	protected String element;
	/** Get property 'element' from 'Part' */
		public String getElement() {
		return element;
	}
	/** Set property 'element' from 'Part' */
		public void setElement(String element) {
		this.element = element;
	}

	/** Property 'type' from 'Part' */
	protected ws.xsd.Type type;
	/** Get property 'type' from 'Part' */
		public ws.xsd.Type getType() {
		return type;
	}
	/** Set property 'type' from 'Part' */
		public void setType(ws.xsd.Type type) {
		this.type = type;
	}

	/** Property 'message' from 'Part' */
	protected Message message;
	/** Get property 'message' from 'Part' */
	public Message getMessage() {
		return message;
	}
	/** Set property 'message' from 'Part' */
	public void setMessage(Message message) { 
		this.message = message;
	}

	/** The id */
	protected String id;
	/** Get the id */
	public String getId() {
		return id;
	}
	/** Set the id */
	public void setId(String id) {
		this.id = id;
	}

	/** Override toString */
	public String toString() {
		String strId = "ws.wsdl.Part";
		String name = null;
		try {
			java.lang.Class cls = this.getClass();
			java.lang.reflect.Method method = cls.getMethod("getName", new java.lang.Class[] {});
			name = (String) method.invoke(this, new Object[] {});
			if (name != null && name.length()==0) name = null;
		} catch (Exception e) {
		}
		if (name == null)
			return strId+" 'id-"+getId()+"'";
		else
			return strId+" '"+name+"-"+getId()+"'";
	}

	/** Delete the object */
	public void delete() {
		if (message != null)
			this.message.getParts().remove(this);
	}

	/** Clone the object */
	public Object clone() {
		Part$Class obj = new Part$Class();
		obj.name = name==null ? null : this.name;
		obj.element = element==null ? null : this.element;
		obj.type = type==null ? null : (ws.xsd.Type)this.type.clone();
		obj.message = message==null ? null : this.message;
		return obj;
	}

	/** Accept 'ws.wsdl.PartVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
