/**
 *
 *  Class Expression.java
 *
 *  Generated by KMFStudio at 22 July 2003 18:50:16
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.yatl.syntax.statements;

import java.util.List;

import uk.ac.kent.cs.yatl.YatlElement;

public interface Expression
extends
    YatlElement
{

	/** Get the 'operands' from 'Expression' */
	public List getOperands();
	/** Set the 'operands' from 'Expression' */
	public void setOperands(List operands);

	/** Get the 'type' from 'Expression' */
	public Object getType();
	/** Set the 'type' from 'Expression' */
	public void setType(Object type);

	/** Get the 'loopStm' from 'Expression' */
	public LoopStm getLoopStm();
	/** Set the 'loopStm' from 'Expression' */
	public void setLoopStm(LoopStm loopStm);

	/** Get the 'ifStm' from 'Expression' */
	public IfStm getIfStm();
	/** Set the 'ifStm' from 'Expression' */
	public void setIfStm(IfStm ifStm);

	/** Get the 'expressionStm' from 'Expression' */
	public ExpressionStm getExpressionStm();
	/** Set the 'expressionStm' from 'Expression' */
	public void setExpressionStm(ExpressionStm expressionStm);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
