/**
 *
 *  Class StereotypeFactory$Class.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms;

public class StereotypeFactory$Class
	extends uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory$Class
	implements StereotypeFactory
{
	/** Default factory constructor */
	public StereotypeFactory$Class() {
	}
	public StereotypeFactory$Class(uk.ac.ukc.cs.kmf.kmfstudio.uml.repository.UmlRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Stereotype obj = new Stereotype$Class();
		obj.setId(uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory$Class.newId());
		repository.addElement("uml.Foundation.Extension_Mechanisms.Stereotype", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Name name, uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.VisibilityKind visibility, Boolean isSpecification, Boolean isRoot, Boolean isLeaf, Boolean isAbstract, String icon, uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Name baseName, uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.Name baseClass) {
		Stereotype obj = new Stereotype$Class(name, visibility, isSpecification, isRoot, isLeaf, isAbstract, icon, baseName, baseClass);
		obj.setId(uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory$Class.newId());
		repository.addElement("uml.Foundation.Extension_Mechanisms.Stereotype", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "StereotypeFactory";
	}

	/** Accept 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.StereotypeVisitor' */
	public Object accept(uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlVisitor v, Object data) {
		return v.visit(this, data);
	}
}
