/**
 *
 *  Class StringArray$Factory$Class.java
 *
 *  Generated by KMFStudio at 29 July 2003 10:22:57
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms;

import uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory$Class;
import uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlVisitor;
import uk.ac.ukc.cs.kmf.kmfstudio.uml.repository.UmlRepository;

public class StringArray$Factory$Class
	extends UmlFactory$Class
	implements StringArray$Factory
{
	/** Default factory constructor */
	public StringArray$Factory$Class() {
	}
	public StringArray$Factory$Class(UmlRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		StringArray obj = new StringArray$Class();
		repository.addElement("uml.Foundation.Extension_Mechanisms.StringArray", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "StringArray_Factory";
	}

	/** Accept 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Extension_Mechanisms.StringArray$Visitor' */
	public Object accept(UmlVisitor v, Object data) {
		return v.visit(this, data);
	}
}
