/**
 *
 *  Class umlStartup.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:48
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.startup;

public interface UmlStartup
{
	/** run the startup */
	public void run(uk.ac.ukc.cs.kmf.kmfstudio.uml.repository.UmlRepository rep);
}
