/**
 *
 *  Class UmlHUTNVisitor.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:47
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.repository;

import uk.ac.ukc.cs.kmf.kmfstudio.uml.*;

public interface UmlHUTNVisitor
	extends UmlVisitor
{
}
