/**
 *
 *  Class Assign.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:39
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public interface Assign
extends
    ws.WsElement,
    BasicActivity,
    Activity
{

	/** Get the 'copy' from 'Assign' */
	public java.util.Set getCopy();
	/** Set the 'copy' from 'Assign' */
	public void setCopy(java.util.Set copy);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
