/**
 *
 *  Class BusinessProcessFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class BusinessProcessFactory$Class
	extends ws.WsFactory$Class
	implements BusinessProcessFactory
{
	/** Default factory constructor */
	public BusinessProcessFactory$Class() {
	}
	public BusinessProcessFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		BusinessProcess obj = new BusinessProcess$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.BusinessProcess", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name, ws.bpel.BooleanExpression joinCondition, Boolean suppressJoinFailure, Boolean variableAccessSerializable, String targetNamespace, String queryLanguage, String expressionLanguage) {
		BusinessProcess obj = new BusinessProcess$Class(name, joinCondition, suppressJoinFailure, variableAccessSerializable, targetNamespace, queryLanguage, expressionLanguage);
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.BusinessProcess", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "BusinessProcessFactory";
	}

	/** Accept 'ws.bpel.BusinessProcessVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
