/**
 *
 *  Class CompensateFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:39
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class CompensateFactory$Class
	extends ws.WsFactory$Class
	implements CompensateFactory
{
	/** Default factory constructor */
	public CompensateFactory$Class() {
	}
	public CompensateFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Compensate obj = new Compensate$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Compensate", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name, ws.bpel.BooleanExpression joinCondition, Boolean suppressJoinFailure) {
		Compensate obj = new Compensate$Class(name, joinCondition, suppressJoinFailure);
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Compensate", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "CompensateFactory";
	}

	/** Accept 'ws.bpel.CompensateVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
