/**
 *
 *  Class CorrelationPattern$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class CorrelationPattern$Class
implements
    CorrelationPattern,
    ws.WsVisitable
{
	/** The 'IN' enumerator */
	public static final CorrelationPattern IN = new CorrelationPattern$Class();
	/** The 'OUT' enumerator */
	public static final CorrelationPattern OUT = new CorrelationPattern$Class();
	/** The 'OUT_IN' enumerator */
	public static final CorrelationPattern OUT_IN = new CorrelationPattern$Class();

	/** Default constructors */
	public CorrelationPattern$Class() {
	}

	/** The id */
	protected String id;
	/** Get the id */
	public String getId() {
		return id;
	}
	/** Set the id */
	public void setId(String id) {
		this.id = "1";
	}

	/** Overrride toString */
	public String toString() {
		String res = "CorrelationPattern";
		if (this == IN) res += "::IN";
		if (this == OUT) res += "::OUT";
		if (this == OUT_IN) res += "::OUT_IN";
		return res;
	}
	/** Clone the object */
	public Object clone() {
		CorrelationPattern$Class obj = new CorrelationPattern$Class();
		return obj;
	}
	/** Delete the object */
	public void delete() {
	}

	/** Accept the visitor */
	public Object accept(ws.WsVisitor v, Object obj) {
		return v.visit(this, obj);
	}
}
