/**
 *
 *  Class CorrelationPatternFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class CorrelationPatternFactory$Class
	extends ws.WsFactory$Class
	implements CorrelationPatternFactory
{
	/** Default factory constructor */
	public CorrelationPatternFactory$Class() {
	}
	public CorrelationPatternFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		CorrelationPattern obj = new CorrelationPattern$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.CorrelationPattern", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "CorrelationPatternFactory";
	}

	/** Accept 'ws.bpel.CorrelationPatternVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
