/**
 *
 *  Class CorrelationSet$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class CorrelationSet$Class
implements
	CorrelationSet,
    ws.WsVisitable
{
	/** Default constructor */
	public CorrelationSet$Class() {
		//--- Set property 'name' from 'CorrelationSet' ---
		this.name = null;
		//--- Set property 'correlation' from 'CorrelationSet' ---
		this.correlation = null;
		//--- Set property 'property' from 'CorrelationSet' ---
		this.property = new java.util.LinkedHashSet();
		//--- Set property 'scope' from 'CorrelationSet' ---
		this.scope = null;
	}
	/** Specialized constructor */
	public CorrelationSet$Class(String name) {
		//--- Set property 'name' from 'CorrelationSet' ---
		this.name = name;
		//--- Set property 'correlation' from 'CorrelationSet' ---
		this.correlation = null;
		//--- Set property 'property' from 'CorrelationSet' ---
		this.property = new java.util.LinkedHashSet();
		//--- Set property 'scope' from 'CorrelationSet' ---
		this.scope = null;
	}


	/** Property 'name' from 'CorrelationSet' */
	protected String name;
	/** Get property 'name' from 'CorrelationSet' */
		public String getName() {
		return name;
	}
	/** Set property 'name' from 'CorrelationSet' */
		public void setName(String name) {
		this.name = name;
	}

	/** Property 'correlation' from 'CorrelationSet' */
	protected Correlation correlation;
	/** Get property 'correlation' from 'CorrelationSet' */
	public Correlation getCorrelation() {
		return correlation;
	}
	/** Set property 'correlation' from 'CorrelationSet' */
	public void setCorrelation(Correlation correlation) { 
		this.correlation = correlation;
	}

	/** Property 'property' from 'CorrelationSet' */
	protected java.util.Set property;
	/** Get property 'property' from 'CorrelationSet' */
	public java.util.Set getProperty() {
		return property;
	}
	/** Set property 'property' from 'CorrelationSet' */
	public void setProperty(java.util.Set property) { 
		this.property = property;
	}

	/** Property 'scope' from 'CorrelationSet' */
	protected Scope scope;
	/** Get property 'scope' from 'CorrelationSet' */
	public Scope getScope() {
		return scope;
	}
	/** Set property 'scope' from 'CorrelationSet' */
	public void setScope(Scope scope) { 
		this.scope = scope;
	}

	/** The id */
	protected String id;
	/** Get the id */
	public String getId() {
		return id;
	}
	/** Set the id */
	public void setId(String id) {
		this.id = id;
	}

	/** Override toString */
	public String toString() {
		String strId = "ws.bpel.CorrelationSet";
		String name = null;
		try {
			java.lang.Class cls = this.getClass();
			java.lang.reflect.Method method = cls.getMethod("getName", new java.lang.Class[] {});
			name = (String) method.invoke(this, new Object[] {});
			if (name != null && name.length()==0) name = null;
		} catch (Exception e) {
		}
		if (name == null)
			return strId+" 'id-"+getId()+"'";
		else
			return strId+" '"+name+"-"+getId()+"'";
	}

	/** Delete the object */
	public void delete() {
		if (correlation != null)
			this.correlation.setSet(null);
		java.util.Iterator propertyIt = this.property.iterator();
		while (propertyIt.hasNext()) {
			ws.bpel.Property propertyObj = (ws.bpel.Property)propertyIt.next();
			if (propertyObj != null)
				propertyObj.setCorrelationSet(null);
		}
		if (scope != null)
			this.scope.getCorrelationSet().remove(this);
	}

	/** Clone the object */
	public Object clone() {
		CorrelationSet$Class obj = new CorrelationSet$Class();
		obj.name = name==null ? null : this.name;
		obj.correlation = correlation==null ? null : this.correlation;
		obj.property = property==null ? null : (java.util.Set)((java.util.LinkedHashSet)this.property).clone();
		obj.scope = scope==null ? null : this.scope;
		return obj;
	}

	/** Accept 'ws.bpel.CorrelationSetVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
