/**
 *
 *  Class DurationKindFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class DurationKindFactory$Class
	extends ws.WsFactory$Class
	implements DurationKindFactory
{
	/** Default factory constructor */
	public DurationKindFactory$Class() {
	}
	public DurationKindFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		DurationKind obj = new DurationKind$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.DurationKind", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "DurationKindFactory";
	}

	/** Accept 'ws.bpel.DurationKindVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
