/**
 *
 *  Class EmptyFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class EmptyFactory$Class
	extends ws.WsFactory$Class
	implements EmptyFactory
{
	/** Default factory constructor */
	public EmptyFactory$Class() {
	}
	public EmptyFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Empty obj = new Empty$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Empty", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name, ws.bpel.BooleanExpression joinCondition, Boolean suppressJoinFailure) {
		Empty obj = new Empty$Class(name, joinCondition, suppressJoinFailure);
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Empty", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "EmptyFactory";
	}

	/** Accept 'ws.bpel.EmptyVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
