/**
 *
 *  Class EventHandler.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public interface EventHandler
extends
    ws.WsElement
{

	/** Get the 'onAlarm' from 'EventHandler' */
	public java.util.Set getOnAlarm();
	/** Set the 'onAlarm' from 'EventHandler' */
	public void setOnAlarm(java.util.Set onAlarm);

	/** Get the 'onMessage' from 'EventHandler' */
	public OnMessage getOnMessage();
	/** Set the 'onMessage' from 'EventHandler' */
	public void setOnMessage(OnMessage onMessage);

	/** Get the 'activity' from 'EventHandler' */
	public Activity getActivity();
	/** Set the 'activity' from 'EventHandler' */
	public void setActivity(Activity activity);

	/** Get the 'scope' from 'EventHandler' */
	public Scope getScope();
	/** Set the 'scope' from 'EventHandler' */
	public void setScope(Scope scope);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
