/**
 *
 *  Class FaultHandlerFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class FaultHandlerFactory$Class
	extends ws.WsFactory$Class
	implements FaultHandlerFactory
{
	/** Default factory constructor */
	public FaultHandlerFactory$Class() {
	}
	public FaultHandlerFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		FaultHandler obj = new FaultHandler$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.FaultHandler", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "FaultHandlerFactory";
	}

	/** Accept 'ws.bpel.FaultHandlerVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
