/**
 *
 *  Class FromExpression.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:39
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public interface FromExpression
extends
    ws.WsElement,
    FromSpec
{

	/** Get the 'expression' from 'FromExpression' */
	public String getExpression();
	/** Set the 'expression' from 'FromExpression' */
	public void setExpression(String expression);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
