/**
 *
 *  Class Invoke.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public interface Invoke
extends
    ws.WsElement,
    PartnerActivity,
    Activity
{

	/** Get the 'inputVariable' from 'Invoke' */
	public Variable getInputVariable();
	/** Set the 'inputVariable' from 'Invoke' */
	public void setInputVariable(Variable inputVariable);

	/** Get the 'outputVariable' from 'Invoke' */
	public Variable getOutputVariable();
	/** Set the 'outputVariable' from 'Invoke' */
	public void setOutputVariable(Variable outputVariable);

	/** Get the 'invokeFaultHandler' from 'Invoke' */
	public FaultHandler getInvokeFaultHandler();
	/** Set the 'invokeFaultHandler' from 'Invoke' */
	public void setInvokeFaultHandler(FaultHandler invokeFaultHandler);

	/** Get the 'compensationHandler' from 'Invoke' */
	public Activity getCompensationHandler();
	/** Set the 'compensationHandler' from 'Invoke' */
	public void setCompensationHandler(Activity compensationHandler);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
