/**
 *
 *  Class Link$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:39
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class Link$Class
implements
	Link,
    ws.WsVisitable
{
	/** Default constructor */
	public Link$Class() {
		//--- Set property 'name' from 'Link' ---
		this.name = null;
		//--- Set property 'target' from 'Link' ---
		this.target = null;
		//--- Set property 'flow' from 'Link' ---
		this.flow = null;
		//--- Set property 'source' from 'Link' ---
		this.source = null;
	}
	/** Specialized constructor */
	public Link$Class(String name) {
		//--- Set property 'name' from 'Link' ---
		this.name = name;
		//--- Set property 'target' from 'Link' ---
		this.target = null;
		//--- Set property 'flow' from 'Link' ---
		this.flow = null;
		//--- Set property 'source' from 'Link' ---
		this.source = null;
	}


	/** Property 'name' from 'Link' */
	protected String name;
	/** Get property 'name' from 'Link' */
		public String getName() {
		return name;
	}
	/** Set property 'name' from 'Link' */
		public void setName(String name) {
		this.name = name;
	}

	/** Property 'target' from 'Link' */
	protected Target target;
	/** Get property 'target' from 'Link' */
	public Target getTarget() {
		return target;
	}
	/** Set property 'target' from 'Link' */
	public void setTarget(Target target) { 
		this.target = target;
	}

	/** Property 'flow' from 'Link' */
	protected Flow flow;
	/** Get property 'flow' from 'Link' */
	public Flow getFlow() {
		return flow;
	}
	/** Set property 'flow' from 'Link' */
	public void setFlow(Flow flow) { 
		this.flow = flow;
	}

	/** Property 'source' from 'Link' */
	protected Source source;
	/** Get property 'source' from 'Link' */
	public Source getSource() {
		return source;
	}
	/** Set property 'source' from 'Link' */
	public void setSource(Source source) { 
		this.source = source;
	}

	/** The id */
	protected String id;
	/** Get the id */
	public String getId() {
		return id;
	}
	/** Set the id */
	public void setId(String id) {
		this.id = id;
	}

	/** Override toString */
	public String toString() {
		String strId = "ws.bpel.Link";
		String name = null;
		try {
			java.lang.Class cls = this.getClass();
			java.lang.reflect.Method method = cls.getMethod("getName", new java.lang.Class[] {});
			name = (String) method.invoke(this, new Object[] {});
			if (name != null && name.length()==0) name = null;
		} catch (Exception e) {
		}
		if (name == null)
			return strId+" 'id-"+getId()+"'";
		else
			return strId+" '"+name+"-"+getId()+"'";
	}

	/** Delete the object */
	public void delete() {
		if (target != null)
			this.target.setLink(null);
		if (flow != null)
			this.flow.getLink().remove(this);
		if (source != null)
			this.source.setLink(null);
	}

	/** Clone the object */
	public Object clone() {
		Link$Class obj = new Link$Class();
		obj.name = name==null ? null : this.name;
		obj.target = target==null ? null : this.target;
		obj.flow = flow==null ? null : this.flow;
		obj.source = source==null ? null : this.source;
		return obj;
	}

	/** Accept 'ws.bpel.LinkVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
