/**
 *
 *  Class LinkFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:39
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class LinkFactory$Class
	extends ws.WsFactory$Class
	implements LinkFactory
{
	/** Default factory constructor */
	public LinkFactory$Class() {
	}
	public LinkFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Link obj = new Link$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Link", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		Link obj = new Link$Class(name);
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Link", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "LinkFactory";
	}

	/** Accept 'ws.bpel.LinkVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
