/**
 *
 *  Class PickFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:39
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class PickFactory$Class
	extends ws.WsFactory$Class
	implements PickFactory
{
	/** Default factory constructor */
	public PickFactory$Class() {
	}
	public PickFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Pick obj = new Pick$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Pick", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name, ws.bpel.BooleanExpression joinCondition, Boolean suppressJoinFailure, Boolean createInstance) {
		Pick obj = new Pick$Class(name, joinCondition, suppressJoinFailure, createInstance);
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Pick", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "PickFactory";
	}

	/** Accept 'ws.bpel.PickVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
