/**
 *
 *  Class ThrowFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class ThrowFactory$Class
	extends ws.WsFactory$Class
	implements ThrowFactory
{
	/** Default factory constructor */
	public ThrowFactory$Class() {
	}
	public ThrowFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Throw obj = new Throw$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Throw", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name, ws.bpel.BooleanExpression joinCondition, Boolean suppressJoinFailure, String faultName) {
		Throw obj = new Throw$Class(name, joinCondition, suppressJoinFailure, faultName);
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Throw", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ThrowFactory";
	}

	/** Accept 'ws.bpel.ThrowVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
