/**
 *
 *  Class WaitFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:39
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.bpel;

public class WaitFactory$Class
	extends ws.WsFactory$Class
	implements WaitFactory
{
	/** Default factory constructor */
	public WaitFactory$Class() {
	}
	public WaitFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Wait obj = new Wait$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Wait", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name, ws.bpel.BooleanExpression joinCondition, Boolean suppressJoinFailure, ws.bpel.DurationKind durationKind) {
		Wait obj = new Wait$Class(name, joinCondition, suppressJoinFailure, durationKind);
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.bpel.Wait", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "WaitFactory";
	}

	/** Accept 'ws.bpel.WaitVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
