/**
 *
 *  Class OrderedSetTypeAS.java
 *
 *  Generated by KMFStudio at 13 April 2004 12:05:03
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.ocl20.syntax.ast.types;

public interface OrderedSetTypeAS
extends
    uk.ac.ukc.cs.kmf.ocl20.syntax.SyntaxElement,
    CollectionTypeAS,
    TypeAS
{

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
