/**
 *
 *  Class ChangeabilityKindFactory.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:44
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types;

public interface ChangeabilityKindFactory
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory
{
	/** Default builder */
	public Object build();
}
