/**
 *
 *  Class ChangeabilityKind$Class.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types;

public class ChangeabilityKind$Class
implements
    ChangeabilityKind,
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlVisitable
{
	/** The 'CHANGEABLE' enumerator */
	public static final ChangeabilityKind CHANGEABLE = new ChangeabilityKind$Class();
	/** The 'FROZEN' enumerator */
	public static final ChangeabilityKind FROZEN = new ChangeabilityKind$Class();
	/** The 'ADDONLY' enumerator */
	public static final ChangeabilityKind ADDONLY = new ChangeabilityKind$Class();

	/** Default constructors */
	public ChangeabilityKind$Class() {
	}

	/** The id */
	protected String id;
	/** Get the id */
	public String getId() {
		return id;
	}
	/** Set the id */
	public void setId(String id) {
		this.id = "1";
	}

	/** Overrride toString */
	public String toString() {
		String res = "ChangeabilityKind";
		if (this == CHANGEABLE) res += "::CHANGEABLE";
		if (this == FROZEN) res += "::FROZEN";
		if (this == ADDONLY) res += "::ADDONLY";
		return res;
	}
	/** Clone the object */
	public Object clone() {
		ChangeabilityKind$Class obj = new ChangeabilityKind$Class();
		return obj;
	}
	/** Delete the object */
	public void delete() {
	}

	/** Accept the visitor */
	public Object accept(uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlVisitor v, Object obj) {
		return v.visit(this, obj);
	}
}
