/**
 *
 *  Class MultiplicityRange$Class.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types;

public class MultiplicityRange$Class
implements
	MultiplicityRange,
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlVisitable
{
	/** Default constructor */
	public MultiplicityRange$Class() {
		//--- Set property 'lower' from 'MultiplicityRange' ---
		this.lower = new Integer(0);
		//--- Set property 'upper' from 'MultiplicityRange' ---
		this.upper = new Integer(-1);
		//--- Set property 'multiplicity' from 'MultiplicityRange' ---
		this.multiplicity = null;
	}
	/** Specialized constructor */
	public MultiplicityRange$Class(Integer lower, Integer upper) {
		//--- Set property 'lower' from 'MultiplicityRange' ---
		this.lower = lower;
		//--- Set property 'upper' from 'MultiplicityRange' ---
		this.upper = upper;
		//--- Set property 'multiplicity' from 'MultiplicityRange' ---
		this.multiplicity = null;
	}


	/** Property 'lower' from 'MultiplicityRange' */
	protected Integer lower;
	/** Get property 'lower' from 'MultiplicityRange' */
		public Integer getLower() {
		return lower;
	}
	/** Set property 'lower' from 'MultiplicityRange' */
		public void setLower(Integer lower) {
		this.lower = lower;
	}

	/** Property 'upper' from 'MultiplicityRange' */
	protected Integer upper;
	/** Get property 'upper' from 'MultiplicityRange' */
		public Integer getUpper() {
		return upper;
	}
	/** Set property 'upper' from 'MultiplicityRange' */
		public void setUpper(Integer upper) {
		this.upper = upper;
	}

	/** Property 'multiplicity' from 'MultiplicityRange' */
	protected Multiplicity multiplicity;
	/** Get property 'multiplicity' from 'MultiplicityRange' */
	public Multiplicity getMultiplicity() {
		return multiplicity;
	}
	/** Set property 'multiplicity' from 'MultiplicityRange' */
	public void setMultiplicity(Multiplicity multiplicity) { 
		this.multiplicity = multiplicity;
	}

	/** The id */
	protected String id;
	/** Get the id */
	public String getId() {
		return id;
	}
	/** Set the id */
	public void setId(String id) {
		this.id = id;
	}

	/** Override toString */
	public String toString() {
		String strId = "uml.Foundation.Data_Types.MultiplicityRange";
		String name = null;
		try {
			java.lang.Class cls = this.getClass();
			java.lang.reflect.Method method = cls.getMethod("getName", new java.lang.Class[] {});
			name = (String) method.invoke(this, new Object[] {});
			if (name != null && name.length()==0) name = null;
		} catch (Exception e) {
		}
		if (name == null)
			return strId+" 'id-"+getId()+"'";
		else
			return strId+" '"+name+"-"+getId()+"'";
	}

	/** Delete the object */
	public void delete() {
		if (multiplicity != null)
			this.multiplicity.getRange().remove(this);
	}

	/** Clone the object */
	public Object clone() {
		MultiplicityRange$Class obj = new MultiplicityRange$Class();
		obj.lower = lower==null ? null : this.lower;
		obj.upper = upper==null ? null : this.upper;
		obj.multiplicity = multiplicity==null ? null : this.multiplicity;
		return obj;
	}

	/** Accept 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.MultiplicityRangeVisitor' */
	public Object accept(uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlVisitor v, Object data) {
		return v.visit(this, data);
	}
}
