/**
 *
 *  Class Name.java
 *
 *  Generated by KMFStudio at 14 April 2004 22:36:44
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types;

public interface Name
extends
    uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlElement
{

	/** Get the 'body_' from 'Name' */
	public String getBody_();
	/** Set the 'body_' from 'Name' */
	public void setBody_(String body_);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
