/**
 *
 *  Class ScopeKind$Factory$Class.java
 *
 *  Generated by KMFStudio at 29 July 2003 10:22:57
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types;

import uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlFactory$Class;
import uk.ac.ukc.cs.kmf.kmfstudio.uml.UmlVisitor;
import uk.ac.ukc.cs.kmf.kmfstudio.uml.repository.UmlRepository;

public class ScopeKind$Factory$Class
	extends UmlFactory$Class
	implements ScopeKind$Factory
{
	/** Default factory constructor */
	public ScopeKind$Factory$Class() {
	}
	public ScopeKind$Factory$Class(UmlRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		ScopeKind obj = new ScopeKind$Class();
		repository.addElement("uml.Foundation.Data_Types.ScopeKind", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ScopeKind_Factory";
	}

	/** Accept 'uk.ac.ukc.cs.kmf.kmfstudio.uml.Foundation.Data_Types.ScopeKind$Visitor' */
	public Object accept(UmlVisitor v, Object data) {
		return v.visit(this, data);
	}
}
