/**
 *
 *  Class AndCompound$Factory$Class.java
 *
 *  Generated by KMFStudio at 25 November 2003 13:01:02
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.as;

public class AndCompound$Factory$Class
	extends sd.SdFactory$Class
	implements AndCompound$Factory
{
	/** Default factory constructor */
	public AndCompound$Factory$Class() {
	}
	public AndCompound$Factory$Class(sd.repository.SdRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		AndCompound obj = new AndCompound$Class();
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.AndCompound", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		AndCompound obj = new AndCompound$Class(name);
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.AndCompound", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "AndCompound_Factory";
	}

	/** Accept 'sd.as.AndCompound$Visitor' */
	public Object accept(sd.SdVisitor v, Object data) {
		return v.visit(this, data);
	}
}
