/**
 *
 *  Class CompoundDiagram.java
 *
 *  Generated by KMFStudio at 18 February 2004 20:38:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.as;

public interface CompoundDiagram
extends
    sd.SdElement,
    Diagram
{

	/** Get the 'children' from 'CompoundDiagram' */
	public java.util.List getChildren();
	/** Set the 'children' from 'CompoundDiagram' */
	public void setChildren(java.util.List children);

	/** Get the 'unitaryParts' from 'CompoundDiagram' */
	public java.util.List getUnitaryParts();
	/** Set the 'unitaryParts' from 'CompoundDiagram' */
	public void setUnitaryParts(java.util.List unitaryParts);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
