/**
 *
 *  Class CompoundDiagramFactory.java
 *
 *  Generated by KMFStudio at 18 February 2004 20:38:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.as;

public interface CompoundDiagramFactory
extends
    sd.SdFactory
{
	/** Default builder */
	public Object build();
	/** Specialized builder */
	public Object build(String name);
}
