/**
 *
 *  Class Contour$Factory$Class.java
 *
 *  Generated by KMFStudio at 25 November 2003 13:01:02
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.as;

public class Contour$Factory$Class
	extends sd.SdFactory$Class
	implements Contour$Factory
{
	/** Default factory constructor */
	public Contour$Factory$Class() {
	}
	public Contour$Factory$Class(sd.repository.SdRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Contour obj = new Contour$Class();
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.Contour", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		Contour obj = new Contour$Class(name);
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.Contour", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "Contour_Factory";
	}

	/** Accept 'sd.as.Contour$Visitor' */
	public Object accept(sd.SdVisitor v, Object data) {
		return v.visit(this, data);
	}
}
