/**
 *
 *  Class ContourFactory$Class.java
 *
 *  Generated by KMFStudio at 18 February 2004 20:38:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.as;

public class ContourFactory$Class
	extends sd.SdFactory$Class
	implements ContourFactory
{
	/** Default factory constructor */
	public ContourFactory$Class() {
	}
	public ContourFactory$Class(sd.repository.SdRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Contour obj = new Contour$Class();
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.Contour", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		Contour obj = new Contour$Class(name);
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.Contour", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ContourFactory";
	}

	/** Accept 'sd.as.ContourVisitor' */
	public Object accept(sd.SdVisitor v, Object data) {
		return v.visit(this, data);
	}
}
