/**
 *
 *  Class NotCompoundFactory$Class.java
 *
 *  Generated by KMFStudio at 18 February 2004 20:38:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.as;

public class NotCompoundFactory$Class
	extends sd.SdFactory$Class
	implements NotCompoundFactory
{
	/** Default factory constructor */
	public NotCompoundFactory$Class() {
	}
	public NotCompoundFactory$Class(sd.repository.SdRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		NotCompound obj = new NotCompound$Class();
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.NotCompound", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		NotCompound obj = new NotCompound$Class(name);
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.NotCompound", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "NotCompoundFactory";
	}

	/** Accept 'sd.as.NotCompoundVisitor' */
	public Object accept(sd.SdVisitor v, Object data) {
		return v.visit(this, data);
	}
}
