/**
 *
 *  Class TrueDiagram$Factory$Class.java
 *
 *  Generated by KMFStudio at 25 November 2003 13:01:02
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.as;

public class TrueDiagram$Factory$Class
	extends sd.SdFactory$Class
	implements TrueDiagram$Factory
{
	/** Default factory constructor */
	public TrueDiagram$Factory$Class() {
	}
	public TrueDiagram$Factory$Class(sd.repository.SdRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		TrueDiagram obj = new TrueDiagram$Class();
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.TrueDiagram", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		TrueDiagram obj = new TrueDiagram$Class(name);
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.TrueDiagram", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "TrueDiagram_Factory";
	}

	/** Accept 'sd.as.TrueDiagram$Visitor' */
	public Object accept(sd.SdVisitor v, Object data) {
		return v.visit(this, data);
	}
}
