/**
 *
 *  Class TrueDiagramFactory$Class.java
 *
 *  Generated by KMFStudio at 18 February 2004 20:38:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.as;

public class TrueDiagramFactory$Class
	extends sd.SdFactory$Class
	implements TrueDiagramFactory
{
	/** Default factory constructor */
	public TrueDiagramFactory$Class() {
	}
	public TrueDiagramFactory$Class(sd.repository.SdRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		TrueDiagram obj = new TrueDiagram$Class();
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.TrueDiagram", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		TrueDiagram obj = new TrueDiagram$Class(name);
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.TrueDiagram", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "TrueDiagramFactory";
	}

	/** Accept 'sd.as.TrueDiagramVisitor' */
	public Object accept(sd.SdVisitor v, Object data) {
		return v.visit(this, data);
	}
}
