/**
 *
 *  Class UnitaryDiagram.java
 *
 *  Generated by KMFStudio at 18 February 2004 20:38:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.as;

public interface UnitaryDiagram
extends
    sd.SdElement,
    Diagram
{

	/** Get the 'zones' from 'UnitaryDiagram' */
	public java.util.List getZones();
	/** Set the 'zones' from 'UnitaryDiagram' */
	public void setZones(java.util.List zones);

	/** Get the 'shadedZones' from 'UnitaryDiagram' */
	public java.util.List getShadedZones();
	/** Set the 'shadedZones' from 'UnitaryDiagram' */
	public void setShadedZones(java.util.List shadedZones);

	/** Get the 'spiders' from 'UnitaryDiagram' */
	public java.util.List getSpiders();
	/** Set the 'spiders' from 'UnitaryDiagram' */
	public void setSpiders(java.util.List spiders);

	/** Get the 'contours' from 'UnitaryDiagram' */
	public java.util.List getContours();
	/** Set the 'contours' from 'UnitaryDiagram' */
	public void setContours(java.util.List contours);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
