/**
 *
 *  Class ZoneFactory$Class.java
 *
 *  Generated by KMFStudio at 18 February 2004 20:38:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package sd.as;

public class ZoneFactory$Class
	extends sd.SdFactory$Class
	implements ZoneFactory
{
	/** Default factory constructor */
	public ZoneFactory$Class() {
	}
	public ZoneFactory$Class(sd.repository.SdRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		Zone obj = new Zone$Class();
		obj.setId(sd.SdFactory$Class.newId());
		repository.addElement("sd.as.Zone", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ZoneFactory";
	}

	/** Accept 'sd.as.ZoneVisitor' */
	public Object accept(sd.SdVisitor v, Object data) {
		return v.visit(this, data);
	}
}
