/**
 *
 *  Class EdocFactoryAdapter$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.repository;

import uk.ac.kent.cs.kmf.xmi.*;
import uk.ac.kent.cs.kmf.util.*;

public class EdocFactoryAdapter$Class
	extends AdapterFactory
	implements IAdapterFactory
{
	/** The repository */
	edoc.repository.EdocRepository rep;
	/** The log */
	ILog log;

	/** AdapterFactory constructor */
	public EdocFactoryAdapter$Class(edoc.repository.EdocRepository rep, ILog log) {
		this.rep = rep;
		this.log = log;
	}

	/** Create a ReaderAdapter */
	public ReaderAdapter createReaderAdapter() {
		return new EdocReaderAdapter$Class(rep, log);
	}

	/** Create a WriterAdapter */
	public WriterAdapter createWriterAdapter() {
		return new WriterAdapter();
	}
}
