/**
 *
 *  Class SyntaxElement.java
 *
 *  Generated by KMFStudio at 13 April 2004 12:05:03
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.ukc.cs.kmf.ocl20.syntax;

public interface SyntaxElement
	extends SyntaxVisitable
{
	/** Override toString */
	public String toString();
}
