/**
 *
 *  Class javaModelStartup.java
 *
 *  Generated by KMFStudio at 22 February 2004 15:13:04
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package javaModel.startup;

public interface JavaModelStartup
{
	/** run the startup */
	public void run(javaModel.repository.JavaModelRepository rep);
}
