/**
 *
 *  Class ComplexTypeFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 13:29:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package ws.xsd;

public class ComplexTypeFactory$Class
	extends ws.WsFactory$Class
	implements ComplexTypeFactory
{
	/** Default factory constructor */
	public ComplexTypeFactory$Class() {
	}
	public ComplexTypeFactory$Class(ws.repository.WsRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		ComplexType obj = new ComplexType$Class();
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.xsd.ComplexType", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		ComplexType obj = new ComplexType$Class(name);
		obj.setId(ws.WsFactory$Class.newId());
		repository.addElement("ws.xsd.ComplexType", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "ComplexTypeFactory";
	}

	/** Accept 'ws.xsd.ComplexTypeVisitor' */
	public Object accept(ws.WsVisitor v, Object data) {
		return v.visit(this, data);
	}
}
