/**
 *
 *  Class SyntaxVisitor.java
 *
 *  Generated by KMFStudio at 11 June 2003 13:46:50
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.syntax;

public class SyntaxVisitor$Class {
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.contexts.VariableDeclarationAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.contexts.VariableDeclarationAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.contexts.PackageDeclarationAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.contexts.PackageDeclarationAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.contexts.ClassifierContextDeclAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.contexts.ClassifierContextDeclAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.contexts.PropertyContextDeclAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.contexts.PropertyContextDeclAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.contexts.OperationContextDeclAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.contexts.OperationContextDeclAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.contexts.ConstraintAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.contexts.ConstraintAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.contexts.ContextDeclarationAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.contexts.ContextDeclarationAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.contexts.ConstraintKindAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.contexts.ConstraintKindAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.contexts.OperationAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.contexts.OperationAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.types.BagTypeAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.types.BagTypeAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.types.TupleTypeAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.types.TupleTypeAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.types.OrderedSetTypeAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.types.OrderedSetTypeAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.types.ClassifierAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.types.ClassifierAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.types.SetTypeAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.types.SetTypeAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.types.SequenceTypeAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.types.SequenceTypeAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.types.TypeAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.types.TypeAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.types.CollectionTypeAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.types.CollectionTypeAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.TupleLiteralExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.TupleLiteralExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.IteratorExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.IteratorExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.OclMessageExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.OclMessageExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.PrimaryExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.PrimaryExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.ArrowSelectionExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.ArrowSelectionExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.IfExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.IfExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.RealLiteralExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.RealLiteralExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.OperationCallExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.OperationCallExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.LoopExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.LoopExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.StringLiteralExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.StringLiteralExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.IterateExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.IterateExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.ImpliesExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.ImpliesExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.SelectionExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.SelectionExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.LiteralExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.LiteralExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.OclMessageKindAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.OclMessageKindAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.AndExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.AndExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.OclMessageArgAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.OclMessageArgAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.OclExpressionAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.OclExpressionAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.BooleanLiteralExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.BooleanLiteralExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.CollectionKindAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.CollectionKindAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.CollectionRangeAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.CollectionRangeAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.XorExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.XorExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.IntegerLiteralExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.IntegerLiteralExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.NotExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.NotExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.OrExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.OrExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.CollectionLiteralExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.CollectionLiteralExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.DotSelectionExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.DotSelectionExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.LogicalExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.LogicalExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.CollectionItemAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.CollectionItemAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.EnumLiteralExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.EnumLiteralExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.AssociationCallExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.AssociationCallExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.PrimitiveLiteralExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.PrimitiveLiteralExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.CallExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.CallExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.PathNameExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.PathNameExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.LetExpAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.LetExpAS host, Object data) {
		return null;
	}
	/** Visit class 'uk.ac.kent.cs.ocl20.syntax.ast.expressions.CollectionLiteralPartAS' */
	public Object visit(uk.ac.kent.cs.ocl20.syntax.ast.expressions.CollectionLiteralPartAS host, Object data) {
		return null;
	}
}
