/**
 *
 *  Class DataEvent.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.Event;

public interface DataEvent
extends
    edoc.EdocElement,
    BusinessEvent
{

	/** Get the 'eventContext' from 'DataEvent' */
	public EventBasedDataManager getEventContext();
	/** Set the 'eventContext' from 'DataEvent' */
	public void setEventContext(EventBasedDataManager eventContext);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
