/**
 *
 *  Class DataEventFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:37
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.Event;

public class DataEventFactory$Class
	extends edoc.EdocFactory$Class
	implements DataEventFactory
{
	/** Default factory constructor */
	public DataEventFactory$Class() {
	}
	public DataEventFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		DataEvent obj = new DataEvent$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.Event.DataEvent", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "DataEventFactory";
	}

	/** Accept 'edoc.ECA.Event.DataEventVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
