/**
 *
 *  Class EventBasedDataManager.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.Event;

public interface EventBasedDataManager
extends
    edoc.EdocElement,
    edoc.ECA.EntityPkg.DataManager,
    EventBasedProcess,
    edoc.ECA.CCA.ProcessComponent,
    edoc.ECA.CCA.Choreography,
    Subscriber,
    Publisher,
    edoc.ECA.CCA.PortOwner,
    edoc.ECA.CCA.Composition,
    edoc.ECA.CCA.UsageContext
{

	/** Get the 'dataEvents' from 'EventBasedDataManager' */
	public java.util.Set getDataEvents();
	/** Set the 'dataEvents' from 'EventBasedDataManager' */
	public void setDataEvents(java.util.Set dataEvents);

	/** Get the id */
	public String getId();
	/** Set the id */
	public void setId(String id);

	/** Override the toString */
	public String toString();

	/** Delete the object */
	public void delete();

	/** Clone the object */
	public Object clone();
}
