/**
 *
 *  Class EventNoticeFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:37
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.Event;

public class EventNoticeFactory$Class
	extends edoc.EdocFactory$Class
	implements EventNoticeFactory
{
	/** Default factory constructor */
	public EventNoticeFactory$Class() {
	}
	public EventNoticeFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		EventNotice obj = new EventNotice$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.Event.EventNotice", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		EventNotice obj = new EventNotice$Class(name);
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.Event.EventNotice", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "EventNoticeFactory";
	}

	/** Accept 'edoc.ECA.Event.EventNoticeVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
