/**
 *
 *  Class PubSubNoticeFactory$Class.java
 *
 *  Generated by KMFStudio at 09 March 2004 11:42:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package edoc.ECA.Event;

public class PubSubNoticeFactory$Class
	extends edoc.EdocFactory$Class
	implements PubSubNoticeFactory
{
	/** Default factory constructor */
	public PubSubNoticeFactory$Class() {
	}
	public PubSubNoticeFactory$Class(edoc.repository.EdocRepository repository) {
		this.repository = repository;
	}

	/** Default build method */
	public Object build() {
		PubSubNotice obj = new PubSubNotice$Class();
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.Event.PubSubNotice", obj);
		return obj;
	}
	/** Specialized build method */
	public Object build(String name) {
		PubSubNotice obj = new PubSubNotice$Class(name);
		obj.setId(edoc.EdocFactory$Class.newId());
		repository.addElement("edoc.ECA.Event.PubSubNotice", obj);
		return obj;
	}

	/** Override toString method */
	public String toString() {
		return "PubSubNoticeFactory";
	}

	/** Accept 'edoc.ECA.Event.PubSubNoticeVisitor' */
	public Object accept(edoc.EdocVisitor v, Object data) {
		return v.visit(this, data);
	}
}
