/**
 *
 *  Class CollectionLiteralPart.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:41
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package uk.ac.kent.cs.ocl20.semantics.model.expressions;

import uk.ac.kent.cs.ocl20.semantics.SemanticsElement;

public interface CollectionLiteralPart
extends
    SemanticsElement
{

	/** Get the 'type' from 'CollectionLiteralPart' */
	public uk.ac.kent.cs.ocl20.semantics.bridge.Classifier getType();
	/** Set the 'type' from 'CollectionLiteralPart' */
	public void setType(uk.ac.kent.cs.ocl20.semantics.bridge.Classifier type);

	/** Get the 'collectionLiteralExp' from 'CollectionLiteralPart' */
	public CollectionLiteralExp getCollectionLiteralExp();
	/** Set the 'collectionLiteralExp' from 'CollectionLiteralPart' */
	public void setCollectionLiteralExp(CollectionLiteralExp collectionLiteralExp);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
